---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86178.
--- DateTime: 2025/10/24 10:15
---
-- 1.参数列表
-- 1.1优惠券id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]

--2数据key
-- 2.1库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2订单id
local orderKey = 'seckill:order' .. voucherId

--3.脚本业务
-- 3.1判读用户是否下单 SISMEMBER order userId
if(redis.call('simember',orderKey,userId)==1)then
    -- 3.3存在，说明是重复下单 返回2
    return 2
end
-- 3.4扣库存
redis.call('incrby',stockKey,-1)
-- .3.5下单
redis.call('sadd',orderKey,userId)
return 0;