// 高性能秒杀 · 10 道主问题
// 所有答案基于 D:\hm-dianping 源码实证，标注 文件:行号
module.exports = {
  outFile: "高性能秒杀_面试题.docx",
  title: "高性能秒杀 · 面试题与标准答案",
  subtitle: "基于《左常健 · 后端研发简历》Live-Hub 项目经历 + D:\\hm-dianping 源码实证整理。文中类名、方法名、行号均可在仓库中逐条查证；凡源码中未落地的表述，均在每题末尾以「⚠ 简历表述 vs 源码实证」单列，供面试前自查与口径修正。",
  overview:
    "秒杀链路为「Redis Lua 原子预检 → RocketMQ 异步消息 → Consumer 加锁落库」。seckill.lua 在一次原子执行内完成库存判空/判足、一人一单 SISMEMBER 判重、DECR 扣减、SADD 记录已购、HSET 订单详情、LPUSH 兜底队列，返回 0/1/2 三态；入口 VoucherOrderServiceImpl.seckillVoucher 只做资格校验与 asyncSend，成功即返回 orderId，订单此时尚未落库。消费端 SeckillOrderConsumer 以 Redisson 锁串行化，经 selectById 幂等、selectCount 二次校验一人一单，再通过 Feign 调 voucher-service 执行条件更新扣库（stock>0），最后 insert 落单；失败回补 Redis，重试 3 次后交 broker 处理。DB 层用 stock>0 条件更新防超卖，全局订单号由 RedisIdWorker（时间戳+Redis 自增）生成。压测资产仅有 k6 脚本，仓库中不含实测结果数据。",
  overviewBullets: [
    "同步段（入口）：取登录态 → 生成 orderId → EVAL Lua → asyncSend → 返回 orderId，全程 Redis 内存操作",
    "异步段（消费）：Redisson 锁 → 幂等校验 → Feign 扣 DB 库存 → insert 订单 → 清理 Redis 详情",
    "防超卖：Lua 内 DECR 前判 stock>0；DB 侧 UPDATE ... WHERE stock>0 条件更新双重防护",
    "防重复：Lua 内 SISMEMBER/SADD 同脚本原子完成；消费端 selectCount 二次校验（DB 无唯一索引）",
    "可观测：SeckillMetrics 注册 11 个 Micrometer 指标，/actuator/prometheus 暴露",
  ],
  questions: [
    // ---------------- Q1 ----------------
    {
      cat: "链路总览", level: "基础",
      title: "请完整讲一遍秒杀下单的链路：一个请求从网关进来，到订单最终落库，经过了哪些服务、哪些组件、哪些存储？",
      focus: "考察点：端到端链路串讲能力、同步/异步边界的划分依据、各组件职责归属、能否主动说出「为什么这么切」。",
      follows: [
        "为什么要把链路切成「同步资格校验 + 异步落库」两段？如果不切，瓶颈会出现在哪里？",
        "Redis 预扣成功到订单落库之间的窗口期，用户凭 orderId 去查订单会看到什么？这个体验问题怎么处理？",
        "这条链路里，你判断哪一步是真正的性能瓶颈？依据是什么？",
      ],
      blocks: [
        { t: "h", x: "1．入口：Controller（同步段起点）" },
        { t: "code", x: "POST /voucher-order/seckill/{id}\norder-service/.../controller/VoucherOrderController.java:29  @RequestMapping(\"/voucher-order\")\norder-service/.../controller/VoucherOrderController.java:35-38  seckillVoucher(voucherId) → voucherOrderService.seckillVoucher(voucherId)" },
        { t: "p", x: "请求先经 gateway-service(8081)：Spring Cloud Gateway 按 Path 断言路由到 lb://order-service，SaReactorFilter 完成统一登录校验后原样转发（网关未配置任何改写请求头的 filter）。" },
        { t: "h", x: "2．同步段：VoucherOrderServiceImpl.seckillVoucher（:88-133）" },
        { t: "code", x: "① :94   Long userId = UserHolder.getUser().getId();        // 登录态注入，不接受请求参数\n② :96   long orderId = redisIdWorker.nextId(\"order\");        // 全局唯一订单号\n③ :98-101 stringRedisTemplate.execute(SECKILL_SCRIPT, Collections.emptyList(),\n             voucherId.toString(), userId.toString(), String.valueOf(orderId));  // 一次 EVAL\n④ :103-114 result!=0 → 1 库存不足 / 2 不能重复下单，并打点\n⑤ :116-118 构造 SeckillOrderMessage → seckillOrderProducer.sendSeckillOrderMessageAsync(message)\n⑥ :129   return Result.ok(orderId);                       // 立即返回，订单尚未落库" },
        { t: "p", x: "这一步只碰 Redis（内存操作）与 MQ 客户端提交，不触碰 MySQL，因此 RT 在毫秒级。返回给前端的语义是「抢购资格已锁定、订单号已分配」，而不是「订单已创建」。" },
        { t: "h", x: "3．异步段：SeckillOrderConsumer.onMessage（:78-165）" },
        { t: "code", x: "① :86-94   RLock lock = redissonClient.getLock(\"lock:order:\" + orderId);\n             lock.tryLock(10, 30, TimeUnit.SECONDS)\n② :97-102  voucherOrderMapper.selectById(orderId) != null → 已处理，直接 return（幂等）\n③ :104-114 selectCount(userId + voucherId) > 0 → rollbackRedisData + return（一人一单二次校验）\n④ :116      Result deductResult = voucherFeignClient.deductStock(voucherId);\n⑤ :130      voucherOrderMapper.insert(voucherOrder);   // status = 1 未支付\n⑥ :134-137  清理 Redis 订单详情 hash" },
        { t: "h", x: "4．库存落库：voucher-service" },
        { t: "code", x: "voucher-service/.../service/impl/VoucherServiceImpl.java:65-69\nboolean success = seckillVoucherService.update()\n        .setSql(\"stock = stock - 1\")\n        .eq(\"voucher_id\", voucherId)\n        .gt(\"stock\", 0)          // 条件更新，防超卖\n        .update();" },
        { t: "h", x: "5．存储与中间件职责" },
        { t: "p", x: "Redis 承担：库存计数（seckill:stock:{vid}，String）、已购用户集合（seckill:order:{vid}，Set）、订单详情（seckill:order:detail:{vid}，Hash）、待处理/失败队列（List）。RocketMQ 承担异步削峰与重试（topic seckill-order-topic，producer group seckill-producer-group）。MySQL 承担最终落库（tb_voucher_order / tb_seckill_voucher）。" },
        { t: "h", x: "6．为什么切成两段" },
        { t: "p", x: "同步段把「判定能不能买」压到一次 Redis EVAL，把不可控的 DB 写、跨服务 HTTP 调用全部挪到异步段，用 MQ 做蓄水池。好处是入口 RT 与并发承载力解耦于 DB 性能——DB 慢只会拉长落库时间，不会把入口线程池打满。代价是最终一致：用户拿到 orderId 时订单还不存在（见追问 2），以及异步段失败时的数据补偿复杂度。" },
      ],
      sources: [
        "order-service/src/main/java/com/hmdp/order/controller/VoucherOrderController.java:29,35-38",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:88-133",
        "order-service/src/main/resources/seckill.lua:1-51",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:78-165",
        "voucher-service/src/main/java/com/hmdp/voucher/service/impl/VoucherServiceImpl.java:63-77",
        "common/src/main/java/com/hmdp/utils/RedisIdWorker.java:25-39",
        "gateway-service/src/main/resources/application.yaml:12-47",
        "docs/perf-plan/架构演进与性能优化落地方案.md:20-22（链路与容量基线）",
      ],
      gap: {
        claim: "简历：微服务拆分 6 个：Nacos 注册发现与配置中心，Gateway 统一路由，OpenFeign 调用……（隐含「所有接口都经网关可达」）",
        fact: "网关 order-route 断言为 Path=/order/**（gateway-service/src/main/resources/application.yaml:32），但订单控制器映射在 @RequestMapping(\"/voucher-order\")（VoucherOrderController.java:29），秒杀实际路径为 /voucher-order/seckill/{id}；voucher-route 的 Path=/voucher/** 同样匹配不上（首段是 voucher-order 而非 voucher）。而 README.md 5.5 又把 /voucher-order/seckill/{id} 列为对外路径。三处无法自洽。",
        advice: "面试前务必本地实测一次「经 8081 调用秒杀接口」是否 404。若确实不通，正确修法是把断言改为 Path=/voucher-order/**,/order/**（或把控制器统一到 /order 前缀）；被问到路由设计时，主动说明断言与服务内映射前缀的对应关系，这是加分点而非减分点。切忌在面试中直接引用 README 的接口表。",
      },
    },

    // ---------------- Q2 ----------------
    {
      cat: "Lua 原子性", level: "基础",
      title: "seckill.lua 里具体做了什么？三个返回值分别代表什么？为什么必须用 Lua，而不是拆成几条 Redis 命令？",
      focus: "考察点：Redis 单线程模型与脚本原子性语义、脚本逐行理解、竞态窗口的识别能力、KEYS/ARGV 传参规范。",
      follows: [
        "脚本里先 GET 判 nil、再判 stock<=0，这两步能合并吗？为什么要分开写？",
        "Java 侧 KEYS 传的是 Collections.emptyList()、所有参数都走 ARGV、key 在脚本内拼接，这样在 Redis Cluster 下会怎样？",
        "如果 Lua 脚本执行时间过长（比如误写了 KEYS * 或遍历大 Set），会有什么后果？",
      ],
      blocks: [
        { t: "h", x: "1．原子性原理" },
        { t: "p", x: "Redis 采用单线程处理命令（Redis 6+ 的多线程只用于网络读写，命令执行仍是单线程），一个 Lua 脚本提交后作为整体执行，执行期间不会插入任何其他客户端的命令。库存的「读—判—减—记」若拆成多条客户端命令，每一步之间都可能插入其他请求，产生竞态：两个请求都读到 stock=1 → 都判断通过 → 都 DECR → 超卖。Lua 把 N 步压成网络上的一条 EVAL、服务端的一个原子操作，同时把 N-1 次 RTT 压缩为 1 次。" },
        { t: "h", x: "2．脚本逐行解读" },
        { t: "code", x: "order-service/src/main/resources/seckill.lua\nlocal voucherId = ARGV[1]  local userId = ARGV[2]  local orderId = ARGV[3]\nlocal stockKey       = 'seckill:stock:'       .. voucherId   -- 库存计数（String）\nlocal orderKey       = 'seckill:order:'       .. voucherId   -- 已购用户（Set）\nlocal orderDetailKey = 'seckill:order:detail:' .. voucherId  -- 订单详情（Hash）\n\nlocal stock = tonumber(redis.call('GET', stockKey))\nif stock == nil then return 1 end        -- 库存 key 不存在（未预热/丢失）\nif stock <= 0  then return 1 end         -- 库存不足\nif redis.call('SISMEMBER', orderKey, userId) == 1 then return 2 end   -- 一人一单判重\n\nredis.call('DECR',  stockKey)            -- 扣减库存\nredis.call('SADD',  orderKey, userId)    -- 记录已购（判断与写入同脚本，无窗口）\nredis.call('HSET',  orderDetailKey, orderId,\n           cjson.encode({voucherId=voucherId, userId=userId, orderId=orderId}))\nredis.call('LPUSH', 'seckill:order:queue', orderId)   -- 待处理队列\nreturn 0" },
        { t: "h", x: "3．三个返回值的语义与 Java 侧处理" },
        { t: "code", x: "0 → 资格校验通过，构造 SeckillOrderMessage 并 asyncSend      (VoucherOrderServiceImpl.java:116-129)\n1 → 库存不存在 或 库存不足 → incrementStockInsufficient → Result.fail(\"库存不足\")   (:105-108)\n2 → 重复下单 → incrementDuplicateOrder → Result.fail(\"不能重复下单\")              (:109-113)" },
        { t: "p", x: "注意「库存 key 不存在」与「库存不足」被统一归为 1：这是防御性设计——如果新券上线时忘了预热 Redis（VoucherServiceImpl.addSeckillVoucher:58 负责写入），返回 1 并提示「库存不足」，比返回 0 让下游扣一个不存在的库存要安全。" },
        { t: "h", x: "4．为什么不用其它方案" },
        { t: "p", x: "① 分布式锁串行化：能防超卖，但所有请求竞争同一把锁，吞吐骤降，且需处理误删、续期、可重入等一堆细节。② WATCH + MULTI/EXEC 乐观事务：高竞争下大量事务被取消重试，性能差。③ 先 DECR 再判负回补：DECR 与判负之间其他请求会读到已被多扣的库存值，回补与新增购买交错极易出错。④ 直接靠数据库行锁/乐观锁扛：DB 连接数和行锁竞争成为瓶颈，违背「把流量挡在 DB 之外」的设计目标。Lua 的本质是「无锁的原子性」——吞吐只受 Redis 单线程处理能力约束。" },
      ],
      sources: [
        "order-service/src/main/resources/seckill.lua:1-51",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:68-73,88-133",
        "voucher-service/src/main/java/com/hmdp/voucher/service/impl/VoucherServiceImpl.java:56-58（库存预热写入）",
        "docs/perf-plan/架构演进与性能优化落地方案.md:32-33（P0-2/P0-3 对脚本双写与 Cluster 兼容性的批评）",
      ],
      gap: {
        claim: "简历：Redis Lua 完成库存校验扣减与一人一单。",
        fact: "属实。脚本确实在一次原子执行内完成了库存校验、扣减与一人一单（seckill.lua:19-38）。可补充的实测细节是：脚本内共 3 次读（GET/SISMEMBER）+ 4 次写（DECR/SADD/HSET/LPUSH），其中 HSET 与 LPUSH 在下游走 MQ 的场景下是纯冗余写入。",
        advice: "这条可以放心讲。被追问「脚本里几次 IO」时大方承认 HSET/LPUSH 冗余，并说明这是「Redis 侧兜底队列」的遗留设计（实际无消费者），反而体现你对自己的链路有全局判断。",
      },
    },

    // ---------------- Q3 ----------------
    {
      cat: "一人一单", level: "进阶",
      title: "一人一单是怎么保证的？Redis Set 判重够不够？为什么消费端还要再查一次数据库？",
      focus: "考察点：判重时机与判重位置、原子性与幂等的区别、数据库约束作为最终防线的重要性、冗余校验的取舍。",
      follows: [
        "数据库层有没有 (user_id, voucher_id) 唯一索引兜底？如果没有，最坏情况会发生什么？",
        "Lua 里的 SISMEMBER 判重和消费端的 selectCount 判重，功能是否重叠？能否去掉其中一个？",
        "同一用户同时对同一张券发两个请求，Lua 是单线程执行的，能保证只成功一次吗？为什么？",
      ],
      blocks: [
        { t: "h", x: "1．Redis 层：Set 判重（主判据）" },
        { t: "code", x: "seckill.lua:30-32\nif redis.call('SISMEMBER', orderKey, userId) == 1 then return 2 end   -- 判重\n...\nseckill.lua:38\nredis.call('SADD', orderKey, userId)                                   -- 记录已购" },
        { t: "p", x: "「判断」与「写入」在同一个 Lua 脚本内完成，中间不存在任何其他命令插入的窗口，因此不存在「两个并发请求都判定未购买」的竞态。这是本方案相较「先 SISMEMBER 再 SADD 两条命令」的关键差别。" },
        { t: "p", x: "用户标识来自登录态而非请求参数：VoucherOrderServiceImpl.java:94 通过 UserHolder.getUser().getId() 取得（UserHolder 先查 ThreadLocal，未命中则委托 Sa-Token 会话）。不接受前端传 userId，从设计上杜绝了「伪造他人身份重复下单」。" },
        { t: "h", x: "2．消费端：selectCount 二次校验（防御性）" },
        { t: "code", x: "SeckillOrderConsumer.java:104-114\nLong count = voucherOrderMapper.selectCount(new LambdaQueryWrapper<VoucherOrder>()\n        .eq(VoucherOrder::getUserId, userId)\n        .eq(VoucherOrder::getVoucherId, voucherId));\nif (count > 0) { rollbackRedisData(voucherId, userId); return; }" },
        { t: "p", x: "这次校验在语义上与前一步重叠：Redis 已保证同一 userId vouchId 只会有一条消息进入队列。它的真实价值是防御「Redis 数据被误删/回档后重建出重复消息」这类非常规场景。代价是每条消息多一次 DB 查询——perf-plan 明确把这列为优化点（P1-2：orderId 本身就是全局唯一主键，selectById 幂等已足够）。" },
        { t: "h", x: "3．关键缺口：数据库没有唯一索引兜底" },
        { t: "code", x: "docs/SQL/start.sql（tb_voucher_order 建表）\nPRIMARY KEY (`id`),\nKEY `idx_user_id` (`user_id`),\nKEY `idx_voucher_id` (`voucher_id`)\n-- 注意：没有 UNIQUE KEY (user_id, voucher_id)" },
        { t: "p", x: "两张普通索引而非唯一索引。这意味着 Redis 一旦失效（如实例重启且未持久化、或运维误删 key），一人一单就失去了**最后一道防线**。正确做法是补一条 UNIQUE KEY uk_user_voucher (user_id, voucher_id)，让数据库成为不可绕过的最终判据——这也是 README.md:673「数据库唯一索引约束」所声称、但 DDL 中并未落实的内容。" },
        { t: "h", x: "4．追问 3 的答案：能保证只成功一次" },
        { t: "p", x: "可以。两个并发请求对应的两次 EVAL 在 Redis 中被串行执行（单线程处理命令）：第一个请求执行完 SADD 后，第二个请求的 SISMEMBER 必然返回 1 → return 2。所以「同一用户并发两请求」在 Redis 侧只会有一次返回 0。真正的风险不在并发，而在上面的「Redis 状态丢失」场景——这才是唯一索引不可省的原因。" },
      ],
      sources: [
        "order-service/src/main/resources/seckill.lua:30-32,38",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:94",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:104-114",
        "common/src/main/java/com/hmdp/utils/UserHolder.java:24-39",
        "docs/SQL/start.sql:96-111（tb_voucher_order DDL，无唯一索引）",
        "README.md:668-674（秒杀 FAQ 声称有数据库唯一索引约束）",
        "docs/perf-plan/架构演进与性能优化落地方案.md:34（P1-2 selectCount 冗余）",
      ],
      gap: {
        claim: "README FAQ：重复下单的解决方案包含「数据库唯一索引约束」；简历未明确提「唯一索引」但强调「一人一单」。",
        fact: "源码中 tb_voucher_order 只有 KEY idx_user_id / KEY idx_voucher_id 两条普通索引，不存在 UNIQUE KEY (user_id, voucher_id)；全仓 SQL 脚本亦无该约束。实际防线只有 Redis Set + 消费端 selectCount 查询。",
        advice: "这是一条极具杀伤力的追问链。建议面试前**真的把唯一索引补上**（ALTER TABLE tb_voucher_order ADD UNIQUE KEY uk_user_voucher(user_id, voucher_id)），然后就能理直气壮地讲「Redis 做前置判重保证性能，数据库唯一索引做最终兜底保证正确性，两层缺一不可」。若暂不改，则务必在回答里主动指出「当前缺唯一索引，这是已知待改进项」——主动暴露远好过被追问击穿。",
      },
    },

    // ---------------- Q4 ----------------
    {
      cat: "库存扣减", level: "进阶",
      title: "数据库层的库存扣减怎么防超卖？简历里说的「乐观锁兜底」具体是哪种乐观锁？",
      focus: "考察点：条件更新式乐观锁 vs 版本号乐观锁的本质区别、跨服务重复扣减的识别、失败重试路径的幂等性分析。",
      follows: [
        "stock > 0 条件更新和 version 版本号乐观锁有什么区别？各自适用什么场景？",
        "deductStock 在数据库扣减成功后又 decrement 了 Redis 库存，而 Lua 入口已经 DECR 过一次——这不是重复扣减吗？",
        "如果 Feign 扣库存成功、但紧接着订单 insert 失败触发 MQ 重试，会发生什么？",
      ],
      blocks: [
        { t: "h", x: "1．DB 侧：条件更新（不是版本号乐观锁）" },
        { t: "code", x: "voucher-service/.../service/impl/VoucherServiceImpl.java:65-69\nboolean success = seckillVoucherService.update()\n        .setSql(\"stock = stock - 1\")\n        .eq(\"voucher_id\", voucherId)\n        .gt(\"stock\", 0)          // ← 关键：把校验条件下推到 SQL 的 WHERE 中\n        .update();               // 影响行数 = 0 即表示库存不足" },
        { t: "p", x: "生成的 SQL 等价于：UPDATE tb_seckill_voucher SET stock = stock - 1 WHERE voucher_id = ? AND stock > 0。校验与更新在同一条 SQL 内由存储引擎原子完成（InnoDB 对该行加写锁），并发请求会被串行化，stock 永远不会减到负数。" },
        { t: "h", x: "2．两种乐观锁的区别" },
        { t: "p", x: "版本号乐观锁：UPDATE ... SET stock = stock-1, version = version+1 WHERE id = ? AND version = {读取时的旧值}。它需要「先读后写」，用于**检测期间该行是否有任何字段被他人改过**，适合多字段一致性、或存在 ABA 风险、或更新条件不止一个字段的场景。" },
        { t: "p", x: "条件更新式乐观锁：直接把业务约束写进 WHERE（此处是 stock > 0）。它不需要读取旧值，一次往返即可，适合「单字段阈值判断」这一最简单也最常见的场景。本项目 tb_seckill_voucher 表也确实**没有 version 列**（docs/SQL/start.sql:12-21 仅 voucher_id 主键 + stock/时间字段），所以简历里的「乐观锁」在实现上指的只能是条件更新。用哪个取决于业务约束形态，不存在绝对优劣。" },
        { t: "h", x: "3．追问 2：确实是重复扣减（真实缺陷）" },
        { t: "p", x: "把两处代码连起来看，同一笔订单在成功路径上 Redis 库存被扣了两次：" },
        { t: "code", x: "入口：VoucherOrderServiceImpl.java:98 → EVAL seckill.lua → seckill.lua:35 redis.call('DECR', stockKey)   // 第 1 次\n消费：SeckillOrderConsumer.java:116 → Feign deductStock\n      → VoucherServiceImpl.java:75 stringRedisTemplate.opsForValue().decrement(SECKILL_STOCK_KEY + voucherId)   // 第 2 次" },
        { t: "p", x: "即正常下单一次，seckill:stock:{vid} 减少 2。这会造成 Redis 库存被「多扣」，从而提前触发「库存不足」而**少卖**。相对地，回补逻辑 rollbackRedisData（SeckillOrderConsumer.java:176-184）只 INCR 一次，回补与扣减不对称。这个 bug 之所以不致命，是因为 seckill:stock 只是**前置闸门**，真正决定卖多少的是 DB 的 stock 列；但两者长期不收敛会让「Redis 显示售罄但 DB 还有货」的少卖持续发生。修法：deductStock 里去掉对 Redis 的 decrement，让 Redis 只由 Lua 扣减、由 rollback 回补，职责单一化。" },
        { t: "h", x: "4．追问 3：insert 失败会重复扣 DB 库存（更严重）" },
        { t: "p", x: "路径推演：④ Feign deductStock 成功（DB stock -1）→ ⑤ insert 失败（:130-141 抛 RuntimeException）→ MQ 重试 → 重试时 selectById 仍为空（订单本就没插进去）→ selectCount 仍为 0 → **再次执行 deductStock**，DB 再 -1 → 然后 insert。结果是同一笔订单扣了两次真实库存。" },
        { t: "p", x: "根因是「扣库存」这一步没有幂等保护：它的幂等键应该是 orderId，但 deductStock 的入参只有 voucherId。修法有两条：① 把扣减改为「按订单号记账」——新增一张库存流水表以 orderId 做唯一索引，扣减前先占位；② 把 DB 扣减挪到 insert 同一个本地事务里（order-service 直接写 voucher 库，取消跨服务调用），用本地事务的原子性消灭这个不一致窗口。前者保留服务边界，后者牺牲边界换强一致，是典型的取舍题。" },
      ],
      sources: [
        "voucher-service/src/main/java/com/hmdp/voucher/service/impl/VoucherServiceImpl.java:63-77",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:116-122,130-141,176-184",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:96-101",
        "order-service/src/main/resources/seckill.lua:35",
        "docs/SQL/start.sql:12-21（tb_seckill_voucher 无 version 列）",
      ],
      gap: {
        claim: "简历：Redisson 分布式锁 + 乐观锁兜底，压测无超卖。",
        fact: "「乐观锁兜底」属实，但要精确表述为 stock>0 的**条件更新**（VoucherServiceImpl.java:67-68），表上并无 version 列。同时存在两处未在简历中体现的缺陷：Redis 库存被重复扣减（入口 Lua + deductStock 各一次），以及 insert 失败重试时会重复扣 DB 库存（deductStock 无 orderId 级幂等）。「压测无超卖」在仓库中无可复核的实测数据（见 Q8）。",
        advice: "面试时把「无条件更新」讲成「条件更新式乐观锁」，并主动说明它是幂等不了的那一环、需要 orderId 做幂等键——能主动指出这个缺陷并给出两条修法（库存流水表 / 合并本地事务），是非常高的加分项。切勿声称「用 version 乐观锁」，一旦被要求指出 version 字段就会当场卡住。",
      },
    },

    // ---------------- Q5 ----------------
    {
      cat: "消息队列", level: "进阶",
      title: "RocketMQ 在秒杀链路里承担什么角色？用的是事务消息还是普通消息？发送失败怎么办？",
      focus: "考察点：MQ 在削峰解耦中的定位、syncSend/asyncSend 语义与代价、异步回调的线程模型、消息可靠性边界的诚实评估。",
      follows: [
        "为什么用 asyncSend 而不是 syncSend？各自的代价是什么？",
        "asyncSend 的 SendCallback 回调是在哪个线程上执行的？回调里能不能做耗时操作？",
        "MQ 发送失败时，Redis 已经预扣的库存会怎样？用户看到的是什么？",
      ],
      blocks: [
        { t: "h", x: "1．角色：削峰填谷 + 解耦 + 异步化" },
        { t: "p", x: "把「资格校验」与「落库」解耦成两个独立可伸缩的阶段。入口只做 Redis 操作与消息提交（毫秒级返回），DB 写入的速率由消费者掌控，从而实现「瞬时高 QPS 涌入、平稳低速落库」。topic 为 seckill-order-topic，producer group 为 seckill-producer-group（order-service/src/main/resources/application.yaml:31-36），消费 group 为 seckill-order-consumer-group。" },
        { t: "h", x: "2．关键事实：是普通异步消息，不是事务消息" },
        { t: "code", x: "order-service/.../mq/SeckillOrderProducer.java:75-100\nrocketMQTemplate.asyncSend(\n        TOPIC_SECKILL_ORDER,\n        MessageBuilder.withPayload(message).build(),\n        new SendCallback() { onSuccess(...) {...}  onException(...) {...} },\n        3000);\n\n// 全仓 grep 结果：sendMessageInTransaction / @RocketMQTransactionListener\n//               / RocketMQLocalTransactionListener  →  Java 代码 0 命中" },
        { t: "p", x: "依赖为 rocketmq-spring-boot-starter 2.3.1 + rocketmq-client 5.3.1（order-service/pom.xml:120-141），该版本**支持**事务消息，但代码未使用。另外发送时未设置 Tag（仅 MessageBuilder.withPayload(...).build()），只有 DLQ 消息才通过 setHeader(\"reason\"/\"retryCount\") 带了业务 header。" },
        { t: "h", x: "3．asyncSend vs syncSend" },
        { t: "p", x: "syncSend 会阻塞等待 broker 返回 SendResult，超时由 send-message-timeout=3000 控制（application.yaml:35）。在秒杀入口这条路径上，每等一次 broker ack 就多占一次 Tomcat 线程的驻留时间，直接把入口吞吐与 broker 的 RT 绑定。asyncSend 提交即返回（无阻塞），由回调处理结果，从而让入口 RT 与 broker 抖动解耦。" },
        { t: "p", x: "必须说清一个容易踩坑的语义：sendSeckillOrderMessageAsync 的返回值 **true 表示「已提交到客户端发送队列」，不代表消息已成功送达 broker**（方法注释 :73 也明确写了这一点）。而调用方 VoucherOrderServiceImpl.java:119 恰恰把 true 当作「发送成功」来打点 incrementMqSendSuccess——这是一个语义误用。" },
        { t: "p", x: "回调线程：SendCallback 由 RocketMQ 客户端的异步发送线程池（默认 publicExecutor / 内部 asyncSenderExecutor）执行，不是 Tomcat 线程。因此在回调里做耗时业务（重试、落库）会阻塞其他回调的执行，且回调内抛出的异常不会传播给调用方，极易静默失败。正确做法是回调里只做轻量记录，重活交给独立线程池或直接依赖 broker 的重试机制。" },
        { t: "h", x: "4．发送失败的处理（当前是缺陷）" },
        { t: "code", x: "VoucherOrderServiceImpl.java:118-124\nboolean sendSuccess = seckillOrderProducer.sendSeckillOrderMessageAsync(message);\nif (sendSuccess) { seckillMetrics.incrementMqSendSuccess(); }\nelse {\n    seckillMetrics.incrementMqSendFail();\n    log.warn(\"消息发送失败，但Redis已预扣库存，订单将异步处理: orderId={}\", orderId);\n}\n// 无论成功失败，都继续往下走并返回 Result.ok(orderId)" },
        { t: "p", x: "发送失败时：① Redis 预扣的库存**不回滚**（没有补偿调用）；② 用户依然收到 Result.ok(orderId)，被告知秒杀成功；③ 但订单永远不会被创建。净效果是**少卖**——库存被占用却没人买。而且因为 Lua 已经 SADD 了该用户，用户也无法再次下单。这是 perf-plan 认定的 P0-4 问题。" },
        { t: "p", x: "修法方向：① Redis 侧留存的订单详情 Hash（seckill:order:detail:{vid}）本就是为对账准备的，可由定时任务扫描「Redis 有、DB 无」的订单并重投；② 或改用事务消息 / 本地消息表，把「预扣」与「消息发送」纳入同一原子语义；③ 至少应在回调 onException 中触发一次库存回补，而不是静默打日志。" },
      ],
      sources: [
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderProducer.java:32-36,50-64,75-100,102-117",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:116-129",
        "order-service/src/main/resources/application.yaml:31-36",
        "order-service/pom.xml:120-141（rocketmq-spring-boot-starter 2.3.1）",
        "docs/perf-plan/架构演进与性能优化落地方案.md:35（P0-4）、:219（本地消息表改进方案，未落地）",
        "docs/perf-plan/k6-seckill.js:25-48（压测脚本中的 RPS 与阈值设定）",
      ],
      gap: {
        claim: "简历：RocketMQ 事务消息 + 本地事件表防丢防重。",
        fact: "源码中两者均不存在。实际发送方式为 asyncSend 普通异步消息（SeckillOrderProducer.java:75-100）；全仓无 sendMessageInTransaction / @RocketMQTransactionListener / RocketMQLocalTransactionListener；无任何 outbox / 本地消息表（grep outbox|local_message|tb_local_message 仅命中 docs/perf-plan 的「改进方案」章节，明确标注为未落地的规划）。当前「防丢防重」实际依赖：broker 重试（maxReconsumeTimes=3）+ selectById 主键幂等 + Redis 回补。",
        advice: "这是全简历风险最高的一句。强烈建议改写为：「RocketMQ 异步消息削峰，配合消费者主键幂等与重试机制保证最终一致性；事务消息与本地消息表为后续演进方向」。若保留原表述，面试官只要问「你的 RocketMQTransactionListener 里回查逻辑怎么写的」就会立刻暴露。相比之下，主动讲清「当前普通消息的三道防线 + 已知的少卖缺口 + 改进方案」，反而是资深工程师的表达方式。",
      },
    },

    // ---------------- Q6 ----------------
    {
      cat: "幂等与锁", level: "深入",
      title: "消费端怎么保证幂等？幂等键是什么？为什么锁加在消费端而不是秒杀入口？",
      focus: "考察点：幂等键的选择依据、Redisson tryLock 参数语义与看门狗机制、锁粒度的性能影响、消息投递语义的理解。",
      follows: [
        "selectById 幂等和 selectCount 一人一单校验功能重叠吗？能去掉一个吗？",
        "tryLock(10, 30, TimeUnit.SECONDS) 这两个参数分别是什么含义？业务执行超过 30 秒会怎样？",
        "如果把锁改成加在秒杀入口（如按 userId 加锁），系统行为会有什么不同？",
      ],
      blocks: [
        { t: "h", x: "1．幂等键 = orderId" },
        { t: "code", x: "SeckillOrderConsumer.java:97-102\nVoucherOrder existingOrder = voucherOrderMapper.selectById(orderId);\nif (existingOrder != null) { seckillMetrics.incrementMqConsumeSuccess(); return; }" },
        { t: "p", x: "orderId 由 RedisIdWorker.nextId(\"order\")（VoucherOrderServiceImpl.java:96）生成，算法为「时间戳差值左移 32 位 | Redis 当日自增计数」（RedisIdWorker.java:37），全局唯一且趋势递增。它同时是 tb_voucher_order 的主键，因此 selectById 天然是一次主键索引命中的 O(1) 查询——这是最廉价也最可靠的幂等实现：**用数据库主键的唯一性做幂等，而不是另建去重表**。" },
        { t: "p", x: "一个需要注意的细节：消息体里的 retryCount 字段（SeckillOrderMessage）在构造时固定为 0，MQ 重试并不会修改消息体内容，所以消费端读到的 message.getRetryCount() 永远是 0 —— SeckillOrderConsumer.java:159 那句「重试次数已达上限，需要人工干预」的判断**实际上永远不会触发**。真实的重试次数由 broker 内部维护（maxReconsumeTimes=3）。" },
        { t: "h", x: "2．Redisson 锁的两个参数与看门狗" },
        { t: "code", x: "SeckillOrderConsumer.java:86-94,144-148\nString lockKey = \"lock:order:\" + orderId;\nRLock lock = redissonClient.getLock(lockKey);\nboolean locked = lock.tryLock(10, 30, TimeUnit.SECONDS);   // waitTime=10s, leaseTime=30s\n...\nfinally { if (lock.isHeldByCurrentThread()) { lock.unlock(); } }" },
        { t: "p", x: "tryLock(waitTime, leaseTime, unit)：waitTime=10s 是最多等待获取锁的时间，超时返回 false（此处 return 表示放弃本条消息，交给 MQ 重试）；leaseTime=30s 是持锁后自动释放的时间。**显式指定 leaseTime 会关闭 Redisson 的看门狗（watchdog）自动续期**——只有调用无 leaseTime 的 lock()/tryLock(waitTime, unit) 时，看门狗才会每 10 秒续期一次。" },
        { t: "p", x: "业务超过 30 秒的后果：锁自动释放，同一条消息可能被另一个消费者并发处理。但因为有 selectById 幂等兜底，最坏结果只是重复执行一次被幂等挡住，不会产生脏数据。另外 unlock 前用 isHeldByCurrentThread() 判断，避免了「释放他人锁」的问题，这是比手写 SETNX 更规范的地方。" },
        { t: "p", x: "这把锁的实际价值需要客观评估：RocketMQ 的同一条消息在同一消费者组内同一时刻只会投递给一个消费者实例，因此并发重复消费本身不会发生；锁真正防的是「业务执行超时导致 broker 重投、上一次执行尚未结束」的重叠窗口。它的代价是每条消息多一次 Redis RTT——而这正是 perf-plan 统计的「消费端 5 次串行 IO」中的第 1 次（P1-1）。在 orderId 幂等已足够可靠的前提下，这把锁属于可优化项。" },
        { t: "h", x: "3．锁加在入口 vs 加在消费端" },
        { t: "p", x: "入口加锁（如 lock:user:{userId}）能让重复请求更早被拒，用户体验上少一次「下单成功但订单不存在」；但代价是锁竞争被压到同步路径上——秒杀高峰期同一用户（或同一券）的请求全部串行化，入口吞吐下降，且引入了新的死锁/误删风险面。" },
        { t: "p", x: "当前设计把锁放在消费端，锁粒度是 orderId，不同订单之间完全不互斥，因此对吞吐几乎无影响；重复请求由入口的 Lua SISMEMBER 先行挡住（那才是用户粒度的判重）。代价是「重复请求要等到落库阶段才被最终拒绝」——但因为 Redis 侧已经拒绝，这条路径实际上不会被走到。结论：入口用 Redis Set 做无锁判重、消费端用 orderId 锁做串行化兜底，是粒度与开销都合理的分工。" },
      ],
      sources: [
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:58,86-94,97-114,144-148,155-164",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:96",
        "common/src/main/java/com/hmdp/utils/RedisIdWorker.java:25-39",
        "common/src/main/java/com/hmdp/dto/SeckillOrderMessage.java:12-32（retryCount 本地字段）",
        "common/src/main/java/com/hmdp/config/RedissonConfig.java:41-57",
        "docs/perf-plan/架构演进与性能优化落地方案.md:36（P1-1 五次串行 IO）",
      ],
    },

    // ---------------- Q7 ----------------
    {
      cat: "失败处理", level: "深入",
      title: "消费失败怎么处理？死信队列是怎么接的？重试次数上限是靠什么判断的？",
      focus: "考察点：RocketMQ 重试与死信机制、自定义 DLQ 与 broker 系统死信的差别、定时对账任务的生效条件（@EnableScheduling）。",
      follows: [
        "maxReconsumeTimes=3 用完之后，消息会到哪里？是自动进 DLQ 吗？进的是哪个 topic？",
        "SeckillOrderDLQConsumer 把消息写进 seckill:order:pending 之后，谁去消费这些待处理订单？",
        "SeckillConsistencyServiceImpl 上的 @Scheduled(fixedRate=300000) 定时对账，真的在跑吗？",
      ],
      blocks: [
        { t: "h", x: "1．消费端的三条失败路径" },
        { t: "code", x: "SeckillOrderConsumer.java\n一人一单校验失败 → rollbackRedisData(voucherId, userId); return;        // :109-114 不重试\n扣减库存失败     → rollbackRedisData(voucherId, userId); return;        // :117-122 不重试\n订单 insert 失败 → throw new RuntimeException(\"订单插入失败\");          // :138-142 交 MQ 重试\n其它异常         → 记日志 + incrementMqConsumeFail + throw               // :155-164 交 MQ 重试" },
        { t: "p", x: "设计上区分了「业务判定失败」（可回滚、不该重试）与「系统异常」（应重试）。这个划分是正确的：一人一单和库存不足属于确定性失败，重试一百次也不会成功，只会浪费资源。" },
        { t: "h", x: "2．关键事实：自定义死信链路是断的" },
        { t: "code", x: "SeckillOrderDLQConsumer.java:13-16\n@RocketMQMessageListener(topic = SeckillOrderProducer.TOPIC_SECKILL_ORDER_DLQ,\n                         consumerGroup = \"seckill-order-dlq-consumer-group\")\n// TOPIC_SECKILL_ORDER_DLQ = \"seckill-order-dlq-topic\"（SeckillOrderProducer.java:34）\n\n// 而该 topic 的唯一发送方：\nSeckillOrderProducer.java:102  sendToDeadLetterQueue(message, reason)\n// 全仓 grep：该方法没有任何调用点" },
        { t: "p", x: "所以真实情况是：**broker 侧的自动死信与项目的自定义死信是两套互不相干的东西**。maxReconsumeTimes=3 用尽后，RocketMQ 会把消息投递到系统死信 Topic %DLQ%seckill-order-consumer-group（这是 RocketMQ 的默认行为，topic 名带 %DLQ% 前缀），而这个 topic **没有任何消费者**；项目自己写的 SeckillOrderDLQConsumer 监听的是 seckill-order-dlq-topic，却没有生产者往里发。结果就是：真正处理失败的消息躺在系统死信 topic 里无人问津。" },
        { t: "p", x: "正确接法有两种：① 放弃自定义 DLQ，直接新建一个消费者监听 %DLQ%seckill-order-consumer-group；② 在消费端的 catch 中主动调用 sendToDeadLetterQueue 后再 return（不 throw），把控制权收回自己手里。当前代码是「两套都搭了一半」，这是很典型的追问点。" },
        { t: "h", x: "3．重试上限的判断不可靠" },
        { t: "p", x: "SeckillOrderConsumer.java:159 用 message.getRetryCount() >= MAX_RETRY_COUNT 判断，但 retryCount 是消息体的普通字段，构造时固定为 0（SeckillOrderMessage 构造函数），broker 重投时不会修改它，因此该条件恒为 false。真实的重试上限由 @RocketMQMessageListener(maxReconsumeTimes = 3)（:38）交给 broker 执行。" },
        { t: "h", x: "4．待处理队列与定时对账" },
        { t: "code", x: "SeckillConsistencyServiceImpl.java\n:101-124 checkPendingOrders()   → 只 range 读取 pending 列表并解析，不处理\n:127-183 repairInconsistentData() → 只对比 Redis 库存/购买人数 与 DB 订单数并返回报告，不修复\n:185-201 @Scheduled(fixedRate = 300000) scheduledConsistencyCheck() → 只统计 pending 数量并打 warn 日志" },
        { t: "p", x: "三处名为「对账/修复」的方法，实现上都只做**只读检查**，没有任何自动补偿动作。更关键的是：@Scheduled 要生效必须在配置类或启动类上开启 @EnableScheduling，而全仓该注解**只出现在 agent-service/AgentApplication.java:17**；order-service 的 OrderApplication.java:15-19 只有 @SpringBootApplication/@EnableDiscoveryClient/@EnableFeignClients/@MapperScan/@EnableCaching。因此这个「每 5 分钟一次的一致性检查」实际上从未被调度执行。" },
      ],
      sources: [
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:38,109-122,138-142,155-164",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderDLQConsumer.java:13-40",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderProducer.java:34,102-117",
        "order-service/src/main/java/com/hmdp/order/service/impl/SeckillConsistencyServiceImpl.java:101-201",
        "order-service/src/main/java/com/hmdp/order/OrderApplication.java:15-19（无 @EnableScheduling）",
        "agent-service/src/main/java/com/hmdp/agent/AgentApplication.java:17（全仓唯一 @EnableScheduling）",
      ],
      gap: {
        claim: "简历：……防丢防重，压测无超卖（隐含「失败链路完整闭环」）。",
        fact: "失败链路的实际状态是：自定义 DLQ 消费无生产者、broker 系统死信无消费者、pending 列表只写不读、定时对账因缺 @EnableScheduling 从未执行、repair 接口只诊断不修复。真正生效的兜底只有「broker 重试 3 次」和「selectById 幂等」。",
        advice: "这条链路一旦被追问会连环崩塌，务必优先补齐。最小改动清单：(1) OrderApplication 加 @EnableScheduling；(2) 消费端 catch 里改为调用 sendToDeadLetterQueue 后 return；(3) repairInconsistentData 补上实际修复动作（按 orderId 幂等重投或回补 Redis）。补齐后，「失败订单进入死信 → 落 pending 列表 → 定时对账扫描 → 人工/自动修复」就是一段非常完整、很有说服力的可靠性设计叙述。",
      },
    },

    // ---------------- Q8 ----------------
    {
      cat: "压测验证", level: "深入",
      title: "「压测无超卖」这个结论是怎么得出来的？压测方案是怎么设计的？",
      focus: "考察点：压测工具与模型选择、阈值设定依据、验证「不超卖」的正确断言方式、对无实测数据的诚实态度。",
      follows: [
        "k6 脚本为什么用 ramping-arrival-rate 而不是 constant-vus？两种模型测量的是不同的东西吗？",
        "thresholds 里 p(99) < 100ms 和 error rate < 0.01 这两个阈值是怎么定的？是拍脑袋吗？",
        "如果要从零设计一套能真正证明「无超卖、无重复下单」的验证方案，你会怎么做？",
      ],
      blocks: [
        { t: "h", x: "1．仓库现状：有脚本，无结果" },
        { t: "code", x: "docs/perf-plan/ 目录全部内容：\n  ├─ k6-seckill.js                  ← 唯一压测资产，压的是秒杀接口\n  └─ 架构演进与性能优化落地方案.md    ← 方案文档\n\n文档第 5 行自述：\n\"所有代码位置均以 文件路径:行号 标注，所有容量数字均为『测算值，以压测校准为准』。\"" },
        { t: "p", x: "仓库中**没有任何压测报告、结果数据、监控截图或压测台账**；文档中提到的 perf-log-template.md 文件并不存在。也没有针对商户查询接口的压测脚本。因此「压测无超卖」「百万请求稳定」目前是无法在仓库中复核的表述。" },
        { t: "h", x: "2．k6 脚本的设计要点" },
        { t: "code", x: "docs/perf-plan/k6-seckill.js:25-48\nexport const options = {\n  scenarios: {\n    seckill: {\n      executor: 'ramping-arrival-rate',      // 恒定到达率模型，而非恒定并发\n      preAllocatedVUs: 500, maxVUs: 2000,\n      startRate: Math.floor(TARGET_RPS / 4),\n      stages: [\n        { target: TARGET_RPS, duration: '60s'  },   // 爬坡 + 预热（数据丢弃）\n        { target: TARGET_RPS, duration: '300s' },   // 稳态 5 分钟（取数窗口）\n        { target: 0,           duration: '30s'  },  // 收尾\n      ],\n    },\n  },\n  thresholds: {\n    'http_req_duration{name:seckill}': ['p(99)<100'],\n    'seckill_http_error{name:seckill}': ['rate<0.01'],\n  },\n};\n// 请求：POST ${BASE_URL}/order/seckill/${VOUCHER_ID}（:52-53）\n// 用法注释：需 token 池，-e TARGET_RPS=5000 → 10000 → 20000 阶梯加压" },
        { t: "p", x: "为什么用 arrival-rate 而不是 constant-vus：秒杀业务关心的是「每秒到达多少请求」，arrival-rate 由 k6 主动控制 RPS，VU 数量只作为执行器自动伸缩（preAllocatedVUs/maxVUs 是容量上限）；constant-vus 则固定并发数，实际 RPS 会随被测系统 RT 变化而变化——系统越慢，测出的 RPS 越低，反而掩盖了容量问题。用 arrival-rate 才能画出「RT 随 RPS 变化的曲线」，找到真正的拐点。" },
        { t: "p", x: "三段式 stages 的设计也值得说明：第一段爬坡同时充当预热（这部分数据丢弃），第二段 5 分钟稳态才是取数窗口（避免把冷启动抖动算进 p99），第三段收尾避免突兀断流。" },
        { t: "p", x: "关于阈值：p(99)<100ms 的目标是「秒杀入口只做 Redis + MQ 提交，不应出现长尾」，error rate<0.01 允许 1% 的失败（秒杀本身有「库存不足/重复下单」这类正常业务失败，需要通过 seckill_http_error 这个自定义 Counter 与真实错误区分开，否则阈值会被业务失败污染）。注意 k6 的 threshold 是**通过/失败判定**，它证明的是「性能达标」，**不能证明「无超卖」**——这是两个不同性质的命题。" },
        { t: "h", x: "3．如何真正证明「无超卖」" },
        { t: "p", x: "正确做法是「压力 + 数据断言」两步。压力侧：库存设为 S，用远大于 S 的并发请求数（如 10×S）打满；断言侧至少覆盖四条：" },
        { t: "code", x: "① DB 侧：SELECT stock FROM tb_seckill_voucher WHERE voucher_id = ?   → 必须 == 0，不允许为负\n② DB 侧：SELECT COUNT(*) FROM tb_voucher_order WHERE voucher_id = ?   → 必须 == S（不多不少）\n③ 一人一单：SELECT COUNT(DISTINCT user_id) == COUNT(*)              → 相等即无同一用户多单\n④ Redis 侧：GET seckill:stock:{vid} >= 0 且 SCARD(seckill:order:{vid}) == 实际下单用户数\n⑤ 一致性对账：DB 订单数 + 未消费消息数（MQ 堆积）== S - Redis 剩余库存" },
        { t: "p", x: "第 ⑤ 条是最完整的对账式断言，它能同时发现「少卖」与「超卖」两个方向的问题（本项目当前的 MQ 发送失败不回滚、Redis 双重扣减两个缺陷都会在这里暴露）。项目其实已经提供了对账接口 /seckill/consistency/**，但实现只做只读检查（见 Q7），把这个接口补成真正的断言工具，压测结论才站得住。" },
      ],
      sources: [
        "docs/perf-plan/k6-seckill.js:1-10,25-53",
        "docs/perf-plan/架构演进与性能优化落地方案.md:5（数字均为测算值的自述）、:47-56（容量基线）",
        "order-service/src/main/java/com/hmdp/order/service/impl/SeckillConsistencyServiceImpl.java:39-183（对账接口实现）",
        "order-service/src/main/java/com/hmdp/order/metrics/SeckillMetrics.java:38-94（可观测指标）",
      ],
      gap: {
        claim: "简历：在 8 核 16GB 内存环境下……百万请求稳定；高性能秒杀……压测无超卖。",
        fact: "仓库中仅有 k6 压测脚本（docs/perf-plan/k6-seckill.js），无任何实测结果、报告或台账；方案文档明确自述「所有容量数字均为测算值，以压测校准为准」。且脚本的 threshold 只能判定性能指标，无法证明不超卖。",
        advice: "这是最容易被要求「把压测报告发我看看」而当场失分的一条。两种应对：(1) 补做一次压测并留存原始数据（k6 的 --summary-export 输出 JSON + DB 断言 SQL 结果截图），把数字换成真实测出的；(2) 若暂无法补测，把简历改为可验证的表述，如「基于 k6 设计了秒杀压测方案（递增至 20000 RPS），入口设计目标 p99<100ms」，删去「百万请求稳定/无超卖」这类无法佐证的结论。面试中若被追问，坦诚说「脚本已就绪，完整压测报告还在整理」，比含糊其辞更安全。",
      },
    },

    // ---------------- Q9 ----------------
    {
      cat: "容量与演进", level: "深入",
      title: "这套秒杀架构的瓶颈在哪？如果流量再涨 10 倍，你会怎么改？",
      focus: "考察点：容量分析的量化能力、热点 key 问题的本质、Redis Cluster 分片原理、消费端吞吐优化的具体手段。",
      follows: [
        "Redis 单 key 热点（seckill:stock:{vid}）怎么破？上 Redis Cluster 能解决吗？",
        "消费端每条消息有 5 次串行 IO，具体怎么优化？能去掉哪几步？",
        "Lua 脚本里的 6 次读写操作能不能减少？减少后收益有多大？",
      ],
      blocks: [
        { t: "h", x: "1．瓶颈定位（量化）" },
        { t: "code", x: "docs/perf-plan/架构演进与性能优化落地方案.md:47-56（明确标注为测算值）\n gateway       3k~6k QPS     ← Lettuce 连接池 max-active:10 是主要约束\n order 入口     3k~6k QPS     ← 200 个 Tomcat 线程，每请求 2~3 次 Redis RTT\n Redis         5~8w ops/s    ← hot key seckill:stock:{vid} 落单核\n MQ 消费端      500~1000 msg/s / 节点  ← 每条消息 5 次串行 IO，20ms+/条，默认并发 20 线程" },
        { t: "p", x: "结论：**最短板在 MQ 消费端**（每秒 500~1000 条），10 万单需要 100~200 秒才能消化完，入口再快也只是把积压堆到 MQ。其次是网关（连接池 10 个连接，Sa-Token 每请求至少一次 Redis 校验）。" },
        { t: "h", x: "2．追问 1：Redis 单 key 热点，Cluster 解决不了" },
        { t: "p", x: "Redis Cluster 是**按 key 做 CRC16 分片**的：同一个 key 永远映射到同一个 slot、同一个节点。所以 seckill:stock:{vid} 这个单 key 无论集群多大，都只落在某一个节点的单核上。Cluster 解决的是「海量 key 的总容量与总吞吐」，解决不了「单 key 热点」。" },
        { t: "p", x: "真正的手段有三类：① **库存分桶**——把库存拆成 N 份（seckill:stock:{vid}:0 ~ :N-1），请求按 userId 哈希分散到各桶独立 DECR，各桶无竞争，总量校验放在出口；② **本地库存 + 异步汇总**——每个应用节点持有部分库存，本地内存直接扣，异步同步到 Redis/DB，把热点从 Redis 转移到 JVM；③ **请求排队/令牌预分配**——网关层限流把真正到达 Redis 的请求量压到可控范围。另外还需注意：当前 KEYS 传空数组、key 在 Lua 内拼接，上 Cluster 后会因 key 不落同一 slot 直接报 CROSSSLOT 错误（perf-plan P0-3），必须改用 KEYS[] 显式传 key 并加 hash tag（如 seckill:{vid}:stock）。" },
        { t: "h", x: "3．追问 2：消费端吞吐优化" },
        { t: "code", x: "当前每条消息的串行 IO（SeckillOrderConsumer.java:86-137）\n  ① Redisson tryLock           → 1 次 Redis RTT\n  ② selectById                 → 1 次 DB\n  ③ selectCount                → 1 次 DB\n  ④ Feign deductStock          → 1 次 HTTP + 1 次 DB UPDATE + 1 次 Redis DECREMENT\n  ⑤ insert                     → 1 次 DB\n  ⑥ 清理 detail hash           → 1 次 Redis" },
        { t: "p", x: "优化方向按收益排序：① **去掉 ③ selectCount**——orderId 主键幂等已足够，DB 补唯一索引做最终兜底（省 1 次 DB）；② **去掉 ① Redisson 锁**——同一队列同一消息本就串行投递，orderId 幂等足以覆盖重试重叠（省 1 次 Redis RTT）；③ **改批量消费**——RocketMQ 支持批量拉取，一次锁/一次 selectById(IN 列表)/一次批量 insert，把 N 次往返摊成 1 次，这是数量级的提升；④ **DB 扣减改批量原子 SQL**——UPDATE ... SET stock = stock - #{batch} WHERE voucher_id = ? AND stock >= #{batch}，把 N 次扣减合并为 1 次；⑤ 提高消费者并发线程数（受限于 DB 连接池，需同步扩容）。" },
        { t: "h", x: "4．追问 3：精简 Lua" },
        { t: "p", x: "脚本内 3 读 4 写中，真正必需的只有：GET 判库存、SISMEMBER 判重、DECR 扣减、SADD 记录——4 次操作。HSET 订单详情与 LPUSH seckill:order:queue 是冗余的：下游已经走 MQ 投递订单号，Redis 侧这份副本既无消费者（perf-plan P0-2 确认 seckill:order:queue 全仓无消费代码），又在下游成功后被清理（虽然清理 key 拼错，实际没删掉）。删掉这两个写可让单次 EVAL 的耗时明显下降（方案文档测算约降 50%，Redis 承载能力从 ~5w 提升到 ~8w QPS，属测算值）。同时应补上 EXISTS 判断 orderDetailKey 的兜底，或干脆废弃该结构。" },
      ],
      sources: [
        "docs/perf-plan/架构演进与性能优化落地方案.md:30-56（P0 清单与容量基线）、:280（Lua 精简收益测算）",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:86-137",
        "order-service/src/main/resources/seckill.lua:14-49",
        "gateway-service/src/main/resources/application.yaml:64-68（Lettuce pool max-active:10）",
        "order-service/src/main/resources/application.yaml:19-25（order 侧连接池）",
      ],
    },

    // ---------------- Q10 ----------------
    {
      cat: "简历口径对决", level: "深入",
      title: "简历写「RocketMQ 事务消息 + 本地事件表防丢防重」，请具体讲讲这两块的实现。",
      focus: "考察点：这是面试官照简历提问时最可能的落点。考察候选人对事务消息/本地消息表原理的真实理解，以及在「简历写了但代码没做」时能否诚实且专业地应对。",
      follows: [
        "RocketMQ 事务消息的 half message + 事务回查是怎么工作的？你的回查逻辑写在哪个类里？",
        "如果不用事务消息，怎么保证「Redis 预扣成功」与「消息一定发出」这两件事的原子性？",
        "本地消息表方案具体怎么设计？和事务消息相比，优劣各在哪？",
      ],
      blocks: [
        { t: "h", x: "1．先给结论：源码中两者都不存在" },
        { t: "code", x: "全仓检索结果（Java 源码）\n  sendMessageInTransaction        → 0 命中\n  @RocketMQTransactionListener    → 0 命中\n  RocketMQLocalTransactionListener→ 0 命中\n  outbox / local_message / tb_local_message → 仅命中 docs/perf-plan 改进方案章节（未落地）\n\n实际发送：SeckillOrderProducer.java:75-100  rocketMQTemplate.asyncSend(...)" },
        { t: "p", x: "当前「防丢防重」实际依赖的是三件事：① broker 重试（@RocketMQMessageListener(maxReconsumeTimes = 3)）；② 消费端 selectById(orderId) 主键幂等；③ 失败时 rollbackRedisData 回补 Redis。这套组合能防「重复消费」，但**防不住「消息根本没发出去」**——这正是 P0-4 少卖缺口的来源。" },
        { t: "h", x: "2．追问 1：事务消息的原理（通用知识）" },
        { t: "p", x: "RocketMQ 事务消息走两阶段提交：① Producer 发送 half message（半消息）到 broker，消息被持久化但对消费者**不可见**；② broker 确认 half message 写入成功后，Producer 执行本地事务；③ Producer 根据本地事务结果向 broker 发送 commit 或 rollback——commit 则消息转为可投递，rollback 则删除半消息；④ 若 broker 长时间未收到二次确认（Producer 宕机等），会**主动回查**：定时回调 Producer 的 checkLocalTransaction 方法询问本地事务状态，由业务方查询本地事务表/业务数据来回答。实现上需要写一个 @RocketMQTransactionListener 类实现 RocketMQLocalTransactionListener 接口，覆盖 executeLocalTransaction（执行本地事务）与 checkLocalTransaction（回查）两个方法。" },
        { t: "h", x: "3．追问 2：不用事务消息如何保证原子性" },
        { t: "p", x: "本项目场景的难点在于「预扣」发生在 Redis 而不是 DB，无法与 DB 事务绑定。可行的三条路：① **本地消息表（outbox）**——在业务库里加一张消息表，把「写业务数据」与「写一条待发送消息」放进同一个本地事务，由定时任务扫描未发送记录投递 MQ，投递成功后置为已发送；② **Redis 兜底 + 定时对账**——Lua 已经把订单详情写入 seckill:order:detail:{vid}，可以起一个定时任务扫描「Redis 有记录、DB 无订单」的条目重投；③ 事务消息（前提是发送方能拿到本地事务结果）。对本项目而言，第 ② 条是成本最低的（数据结构已经存在），第 ① 条最严谨。" },
        { t: "h", x: "4．追问 3：本地消息表 vs 事务消息" },
        { t: "code", x: "本地消息表（outbox）核心流程\n  1. BEGIN\n  2.   INSERT INTO tb_voucher_order (...)              -- 业务数据\n  3.   INSERT INTO tb_local_message(order_id, payload, status=0)   -- 待发送\n  4. COMMIT                                            -- 两者同事务，原子\n  5. 定时任务：SELECT * FROM tb_local_message WHERE status=0 LIMIT N\n  6. 逐条投递 MQ → 成功则 UPDATE status=1 → 下游按 message_id 幂等消费\n  7. 失败则重试（指数退避），超过阈值告警人工介入" },
        { t: "p", x: "取舍对比：**本地消息表**不依赖 MQ 特性、可移植到任意 MQ、消息内容与状态可审计可重放、可用 SQL 直接排查；代价是额外的表与扫描任务、投递有秒级延迟、需要处理扫描任务的多实例并发（加锁或用 SELECT ... FOR UPDATE SKIP LOCKED）。**事务消息**由 broker 承担可靠性、无额外表、延迟更低；代价是深度绑定 RocketMQ（其他 MQ 无此能力）、必须实现并仔细测试回查逻辑（回查失败会导致消息悬挂）、半消息对业务不可见带来调试难度。选哪个取决于是否愿意为可靠性引入额外的表与运维负担。" },
        { t: "p", x: "对本项目的补充：由于预扣在 Redis，走 outbox 需要一个「Redis 预扣 + DB outbox」的桥接——更贴合的方案其实是把预扣也落到 DB（库存流水表，以 orderId 唯一索引），让整条链路回到单一本地事务内，这也是 Q4 提到的两条修法之一。" },
      ],
      sources: [
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderProducer.java:75-100,102-117",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:35-41,97-102,176-184",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:116-129",
        "order-service/pom.xml:120-141（rocketmq-spring-boot-starter 2.3.1）",
        "docs/perf-plan/架构演进与性能优化落地方案.md:35（P0-4）、:219-225（本地消息表改进方案，未落地）",
      ],
      gap: {
        claim: "简历：高性能秒杀：Redis Lua 完成库存校验扣减与一人一单，RocketMQ 事务消息 + 本地事件表防丢防重，Redisson 分布式锁 + 乐观锁兜底，压测无超卖。",
        fact: "四件事中，Redis Lua 与 Redisson 锁属实；「乐观锁」实为 stock>0 条件更新（表无 version 列）；「事务消息」「本地事件表」在源码中完全没有实现（全仓 0 命中，仅存在于 docs/perf-plan 的规划章节）；「压测无超卖」无可复核的实测数据。",
        advice: "这一题在真实面试中出现的概率极高，因为它是简历原文。推荐的处理是「先改简历 + 再准备一套诚实的纵深回答」：改写为「Redis Lua 原子预扣 + RocketMQ 异步削峰，消费端主键幂等与 broker 重试保证最终一致；事务消息与本地消息表为已设计待落地的演进项（见 docs/perf-plan）」。这样被追问时，你可以自然地讲出事务消息的回查机制、本地消息表的事务内双写与扫描重投、以及两者的取舍——展示的是原理掌握度，而不是背简历。反之，若坚持原表述，面试官只需一句「把你的 RocketMQTransactionListener 打开看看」就会终结这个话题。",
      },
    },
  ],
};
