// 微服务设计 · 6 道主问题
module.exports = {
  outFile: "微服务设计_面试题.docx",
  title: "微服务设计 · 面试题与标准答案",
  subtitle: "基于《左常健 · 后端研发简历》Live-Hub 项目经历 + D:\\hm-dianping 源码实证整理。本板块题量按「10/10/6」配置，因源码中微服务治理组件（Sentinel、链路追踪、配置热更新）落地较少，题量相应收敛；命中率最高的追问集中在网关路由断言与 Seata 现状两处，请重点准备。",
  overview:
    "6 个业务服务（gateway 8081 / shop 8082 / voucher 8083 / order 8084 / social 8085 / user 8086），另有 rag 8087、agent 8088 与公共模块 common（无端口）。Nacos（8848）承担注册发现与配置中心，各服务 bootstrap.yaml 声明服务名/Nacos/Seata，application.yaml 承载数据源与中间件，并通过 spring.config.import: optional:nacos:${name}.yaml 拉取远端配置。Gateway 为纯 yml 声明式路由（全部 uri: lb://，无自定义 filter），SaReactorFilter 做统一登录校验（白名单仅 3 条），AgentRateLimitFilter 对 /agent/** 做 Redis+Lua 令牌桶限流。OpenFeign 跨服务调用仅 2 组业务（order→voucher、social→user），order 侧配了 fallback 与 circuitbreaker。Sa-Token 1.44.0 会话存 Redis 跨服务共享，下游业务服务无任何二次鉴权。Seata 仍 enabled: true 但秒杀主链路已不依赖它，仅遗留 1 处 @GlobalTransactional 在已废弃方法上。5 个业务服务共用 MySQL 的 hmdp 库（未分库）。",
  overviewBullets: [
    "服务发现：各服务 @EnableDiscoveryClient + Nacos，Feign/Gateway 均按服务名调用（lb://、@FeignClient(name=...)）",
    "路由：7 条 yml 路由，predicates 仅用 Path，filters 全为空；全局 CORS 在 yml 中配置",
    "鉴权：网关 SaReactorFilter.checkLogin() 统一拦截；业务服务无拦截器、无 @SaCheckLogin",
    "调用：order→voucher 带 fallback（Feign circuitbreaker enabled），social→user 无 fallback；超时仅 order 配置（5s）",
    "数据：5 个业务服务共库 hmdp；agent 用独立 schema；rag 用 PostgreSQL+pgvector",
  ],
  questions: [
    // ---------------- Q1 ----------------
    {
      cat: "服务拆分", level: "基础",
      title: "你的服务是怎么拆的？拆分依据是什么？几个服务共用一个数据库，这还算微服务吗？",
      focus: "考察点：服务边界划分的依据、跨服务拆分的收益与成本、共享数据库反模式的认知、对自身架构诚实评估的能力。",
      follows: [
        "为什么 voucher 和 order 要拆成两个服务？在秒杀场景下，这个拆分带来了哪些额外成本？",
        "5 个业务服务共用一个库，会有什么问题？你觉得到什么阶段应该拆库？",
        "如果按 DDD 重新划分边界，你会怎么拆？",
      ],
      blocks: [
        { t: "h", x: "1．服务清单与职责" },
        { t: "code", x: "服务名            端口   职责                         核心数据模型\n----------------------------------------------------------------------\ngateway-service   8081   API 网关、路由、登录校验、/agent 频控   —\nshop-service      8082   商户信息、店铺分类、店铺详情          Shop / ShopType\nvoucher-service   8083   优惠券发放、抢购、使用               Voucher / SeckillVoucher\norder-service     8084   订单创建、退款、查询、对账            VoucherOrder\nsocial-service    8085   博客、点赞评论、关注、站内信           Blog / BlogComments / Follow\nuser-service      8086   用户登录、个人信息、签到               User / UserInfo\n----------------------------------------------------------------------\n另有 rag-service(8087)、agent-service(8088)（本次范围外）；common 为公共模块，无端口\n\n依据：各服务 src/main/resources/application.yaml 的 server.port 与 spring.application.name；\n      README.md:47-59 服务划分表（与代码一致）" },
        { t: "h", x: "2．拆分依据" },
        { t: "p", x: "按**业务域**拆分：用户（身份）、商户（供给）、优惠券（资产）、订单（交易）、社交（内容与关系）。这五个域的变更频率、读写特征、数据生命周期各不相同，独立成服务后可以独立发布、独立扩缩容、独立选型。" },
        { t: "p", x: "启动类注解也印证了每个服务都是完整独立的应用：@SpringBootApplication + @EnableDiscoveryClient + @EnableFeignClients + @MapperScan，voucher 额外有 @EnableCaching（各服务 XxxApplication.java:14-19）。" },
        { t: "h", x: "3．追问 1：voucher / order 拆分的收益与成本" },
        { t: "p", x: "收益：券是「资产定义」（模板 + 库存），订单是「交易记录」，两者的读写模式差别很大——券管理的写少读多且可缓存，订单是高并发写入。拆开后秒杀时只需扩容 order-service，不影响券管理。边界也清晰：券的归属是商户，订单的归属是用户。" },
        { t: "p", x: "成本（秒杀场景下尤其明显）：扣库存从「本地方法调用」变成了**跨服务 Feign 调用**（order-service/.../feign/VoucherFeignClient.java:13-14，PUT voucher/seckill/{id}/stock）。这一拆引入了：网络开销（每次落库多一次 HTTP 往返）、超时与重试语义（Feign 超时 5000ms 配在 order-service/application.yaml:119-127）、部分失败的可能（HTTP 成功但响应丢失）、以及分布式一致性难题。**正是因为跨服务写无法用本地事务保证，秒杀链路才演进出「Redis Lua 预扣 + RocketMQ 异步最终一致」这套方案**——这是「拆分成本驱动架构演进」的典型案例，面试时这样串联会非常有说服力。" },
        { t: "h", x: "4．追问 2：共享数据库的问题" },
        { t: "code", x: "5 个业务服务的数据源配置完全相同：\n  user/shop/voucher/order/social 各 application.yaml\n  url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC\n\n对比 docs/md/hmdp微服务拆分方案.md:58 的设计目标：\n  \"按模块拆分数据库，创建5个数据库实例\"\n→ 实际未拆分。README.md:59 已如实说明「业务库统一为 MySQL 的 hmdp 库」。" },
        { t: "p", x: "共享数据库的问题：① **发布耦合**——任何一张表的 DDL 变更都影响所有服务，服务独立发布的能力被数据库抵消；② **边界形同虚设**——一个服务可以（也很容易）直接 join 另一个服务的表，微服务的边界约束退化成约定；③ **资源竞争**——连接池、慢查询、锁等待在服务间互相影响，一个服务的慢 SQL 可能拖垮所有服务；④ **无法按服务独立扩展**——所有服务共享同一个库的容量上限；⑤ **技术选型锁死**——不能针对某个域选择更适合的存储。" },
        { t: "p", x: "拆库时机：当团队规模扩大导致发布互相阻塞、或单库连接数/容量成为瓶颈、或某个域确实需要不同的存储引擎时。拆库的真正难点不在「拆」本身，而在拆完之后**跨库事务与分布式查询**如何处理（这正是 Seata、本地消息表、CQRS 读模型要解决的问题）。对一个学习型项目来说，先共库跑通业务、再按需拆库，是比一步到位更务实的选择。" },
        { t: "h", x: "5．追问 3：按 DDD 重新划分" },
        { t: "p", x: "先做事件风暴识别限界上下文，再定聚合边界。按本项目业务可以划为：① **身份上下文**（用户、登录态、签到）；② **商户上下文**（店铺、分类、地理）；③ **交易上下文**——把 Voucher 与 VoucherOrder 收进同一个上下文，因为它们共享「库存」这个核心不变量（券的库存与订单的成立是强一致的原子操作），拆成两个服务反而是把聚合根劈开了，这正是当前跨服务扣库存痛苦的根源；④ **社交上下文**（博客、关注、Feed）。" },
        { t: "p", x: "此外，**秒杀应当作为独立的高并发子系统**单独演进（独立库、独立 Redis、独立的限流与降级策略），而不是混在 order-service 里与普通订单查询共享同一个实例。这属于按「业务能力」和「技术特征」双重维度拆分。" },
      ],
      sources: [
        "各服务 src/main/resources/application.yaml（server.port / spring.application.name / datasource.url）",
        "README.md:47-59（服务划分表与共库说明）",
        "docs/md/hmdp微服务拆分方案.md:58（原设计目标：拆 5 个库，与实现不符）",
        "order-service/src/main/java/com/hmdp/order/feign/VoucherFeignClient.java:10-18",
        "order-service/src/main/resources/application.yaml:119-127（Feign 超时）",
        "各服务启动类 XxxApplication.java（服务独立性注解）",
      ],
    },

    // ---------------- Q2 ----------------
    {
      cat: "Nacos", level: "基础",
      title: "Nacos 在项目里承担什么角色？配置是怎么加载的？为什么 bootstrap.yaml 和 spring.config.import 两套方式并存？",
      focus: "考察点：注册中心与配置中心的双重职责、Spring Cloud 配置加载机制的演进、optional 与 import-check 的作用、配置热更新的落地条件。",
      follows: [
        "optional: 前缀和 import-check.enabled: false 分别解决什么问题？",
        "你配了 namespace，group 呢？social-service 为什么显式写了 DEFAULT_GROUP？",
        "配置热更新怎么用？项目里 @RefreshScope 用了吗？",
      ],
      blocks: [
        { t: "h", x: "1．Nacos 的双重角色" },
        { t: "code", x: "spring:\n  application:\n    name: order-service\n  cloud:\n    nacos:\n      server-addr: localhost:8848\n      discovery:\n        namespace: public          # 服务发现的命名空间（环境隔离）\n      config:\n        namespace: public          # 配置中心的命名空间\n        file-extension: yaml\n        import-check:\n          enabled: false\n  config:\n    import: optional:nacos:${spring.application.name}.yaml\n\n来源：各服务 src/main/resources/bootstrap.yaml:2-22（内容基本一致）" },
        { t: "p", x: "① **注册中心**（discovery）：服务启动时把 `服务名 → ip:port` 注册到 Nacos，调用方（Gateway 的 `lb://`、Feign 的 `@FeignClient(name=...)`）通过服务名发现实例并做客户端负载均衡。② **配置中心**（config）：集中托管各服务的配置，支持运行时修改。" },
        { t: "p", x: "namespace 用于**环境隔离**（开发/测试/生产各占一个 namespace，互不可见）；group 用于同一 namespace 内的**业务分组**。项目全部使用 public namespace。" },
        { t: "h", x: "2．两套加载方式并存的原因" },
        { t: "p", x: "Spring Cloud 2020 引入了 `spring.config.import`，官方推荐用它替代 bootstrap 机制（bootstrap 需要一个额外的 Bootstrap 上下文，且加载顺序容易让人困惑）。但 `spring-cloud-starter-bootstrap` 在 2022.x 中仍然可用（需显式引入依赖）。" },
        { t: "code", x: "各服务 pom.xml 均引入 spring-cloud-starter-bootstrap 4.1.2\n  gateway-service/pom.xml:48-52、user-service/pom.xml:85-89、shop-service/pom.xml:85-89、\n  voucher-service/pom.xml:85-89、order-service/pom.xml:103-107、social-service/pom.xml:111-115\n\n因此实际形态是两套并存：\n  bootstrap.yaml   → 承载 spring.application.name + nacos 地址 + seata 配置（必须早于 application.yaml 加载）\n  application.yaml → 承载数据源、中间件、业务参数，并提供 spring.config.import 拉取远端配置" },
        { t: "p", x: "之所以两套并存，多半是**历史演进**：项目初期用 bootstrap（当时主流），后来在 application.yaml 里补了 config.import。两者功能上不冲突，但确实存在配置分散、容易让人搞不清「哪个配置从哪来」的问题。规范做法是二选一：新项目建议全用 spring.config.import（把 seata、datasource 都放 application.yaml），或全用 bootstrap。这是一个可以主动提出的改进点。" },
        { t: "h", x: "3．追问 1：optional 与 import-check" },
        { t: "p", x: "`optional:` 前缀的含义是「该配置源可以拉取失败」。如果 Nacos 中不存在 `order-service.yaml` 这个 dataId，没有 optional 会直接启动失败；加了 optional 则静默跳过，用本地 application.yaml 的配置启动。" },
        { t: "p", x: "`import-check.enabled: false` 则是关闭 Spring Cloud 的**导入检查**——在 2021+ 版本中，如果使用了 Nacos config 但没有正确配置 config.import，启动时会抛出明确的错误提示（提示开发者补上 import 配置）。关闭它意味着放弃这层保护，换来的是「即使配置导入有问题也不阻断启动」的容错。" },
        { t: "p", x: "这两个设置合起来说明项目的配置策略是**「远端配置可缺省、以本地配置为准」**——适合同步多个开发者的本地环境，但在生产环境中是危险的：远端配置推送失败会静默降级到本地默认值，可能造成难以排查的行为差异。生产上应当反过来，让配置缺失快速失败。" },
        { t: "p", x: "另外值得说明的是：本项目**没有配置共享 dataId**（全仓无 shared-configs / extension-configs），每个服务只导入自己的 `${spring.application.name}.yaml`，所以跨服务的公共配置（如 Redis 地址、MySQL 地址）在 5 个服务的 application.yaml 里各写了一份，修改时需要改 5 处。正确做法是把公共配置提取成一个 `hmdp-common.yaml` 并用 shared-configs 引入。" },
        { t: "h", x: "4．追问 2：group 的配置" },
        { t: "p", x: "大多数服务只写了 namespace 未写 group——此时使用默认值 `DEFAULT_GROUP`。只有 social-service 显式写了 `group: DEFAULT_GROUP`（social-service/src/main/resources/bootstrap.yaml:14,19），语义上完全等价，属于配置风格不一致，不影响功能。面试时如实说明即可，不必强行解释成设计意图。" },
        { t: "h", x: "5．追问 3：配置热更新未落地" },
        { t: "code", x: "全仓检索结果：\n  @RefreshScope            → 0 命中\n  @NacosValue              → 0 命中\n  ConfigService.addListener → 0 命中" },
        { t: "p", x: "配置中心的能力（动态刷新）在当前项目中**没有被使用**——只用了 Nacos 的配置托管能力，没有用它运行时推送变更的能力。要用的话：在需要热更新的 Bean 上加 `@RefreshScope`，然后在 Nacos 控制台修改配置并发布，Spring Cloud 会触发 RefreshEvent 并重建该 Bean。" },
        { t: "p", x: "需要提醒的坑：`@RefreshScope` 对构造器注入的依赖、final 字段、以及部分已初始化的中间件客户端（如 RedissonClient 的连接地址）无效——刷新只会影响通过 getter 每次重新获取的属性。对于本项目，比较适合热更新的是业务开关类参数（如秒杀是否开启、限流阈值），而不适合数据源、Redis 连接这类基础设施配置。" },
      ],
      sources: [
        "各服务 src/main/resources/bootstrap.yaml:1-41",
        "social-service/src/main/resources/bootstrap.yaml:14,19（显式 group）",
        "各服务 pom.xml（spring-cloud-starter-bootstrap 4.1.2）",
        "order-service/src/main/resources/application.yaml:1-36（本地配置承载内容）",
        "README.md:547-567（配置分工说明与 Nacos 配置示例）",
      ],
    },

    // ---------------- Q3 ----------------
    {
      cat: "网关", level: "进阶",
      title: "网关的路由和鉴权分别是怎么实现的？SaReactorFilter 和 GlobalFilter 有什么区别？",
      focus: "考察点：声明式路由与编程式路由的取舍、过滤器接口的层次、白名单设计的业务合理性，以及能否发现自己路由配置里的问题。",
      follows: [
        "白名单有哪几个？为什么查询类接口（如 /shop/**）也要强制登录，这样合理吗？",
        "你的 order-route 断言是 Path=/order/**，但订单控制器映射在 /voucher-order，这两个能匹配上吗？",
        "网关的限流是怎么做的？Redis 挂了会怎样？",
      ],
      blocks: [
        { t: "h", x: "1．路由：纯 yml 声明式" },
        { t: "code", x: "gateway-service/src/main/resources/application.yaml:12-47\n- id: user-route\n  uri: lb://user-service\n  predicates: [ Path=/user/**,/auth/** ]\n- id: shop-route\n  uri: lb://shop-service\n  predicates: [ Path=/shop/**,/shop-type/** ]\n- id: voucher-route\n  uri: lb://voucher-service\n  predicates: [ Path=/voucher/** ]\n- id: order-route\n  uri: lb://order-service\n  predicates: [ Path=/order/** ]          ← 注意这一行\n- id: social-route\n  uri: lb://social-service\n  predicates: [ Path=/blog/**,/comment/**,/follow/**,/notification/** ]\n- id: rag-route\n  uri: lb://rag-service\n  predicates: [ Path=/api/rag/** ]\n- id: agent-route\n  uri: lb://agent-service\n  predicates: [ Path=/agent/** ]\n\n全部路由均未配置 filters（无 StripPrefix / RewritePath / AddRequestHeader）" },
        { t: "p", x: "`lb://` 表示使用 Spring Cloud LoadBalancer 做客户端负载均衡（各服务 pom 均引入 spring-cloud-starter-loadbalancer），从 Nacos 拉取实例列表后按默认轮询策略选择。因为所有路由都不做前缀改写，各服务的 Controller 必须自带与断言一致的前缀——这也是下面那个问题的根源。" },
        { t: "p", x: "另外还配置了全局 CORS（:48-57，allowed-origin-patterns 为 `*`、allow-credentials 为 true）与 Actuator 端点暴露（:79-88，include: health,info,gateway）。" },
        { t: "h", x: "2．鉴权：SaReactorFilter" },
        { t: "code", x: "gateway-service/.../config/SaTokenGatewayConfig.java:21-41\n@Bean\npublic SaReactorFilter saReactorFilter() {\n    return new SaReactorFilter()\n            .addInclude(\"/**\")                                        // 拦截所有请求\n            .addExclude(\"/user/login\", \"/user/code\", \"/actuator/**\") // 白名单：仅 3 条\n            .setAuth(obj -> {\n                SaRouter.match(\"/**\", r -> StpUtil.checkLogin());     // 统一校验登录\n            })\n            .setError(e -> { ... 返回统一 Result JSON ... });\n}" },
        { t: "h", x: "3．追问 1：SaReactorFilter vs GlobalFilter" },
        { t: "code", x: "GlobalFilter（Spring Cloud Gateway 原生全局过滤器接口）\n  Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain);\n  → 需要自己处理请求放行、响应写回、以及通过 Ordered 控制执行顺序\n  → 项目中的实例：AgentRateLimitFilter（implements GlobalFilter, Ordered，getOrder() 返回 -10）\n\nSaReactorFilter（Sa-Token 针对 WebFlux 的封装）\n  → 把「路径匹配 + 放行规则 + 异常处理」做成声明式 DSL\n  → 底层仍是一个 WebFilter，只是把样板代码封装掉了" },
        { t: "p", x: "两者不是竞争关系：GlobalFilter 是 Spring Cloud Gateway 的框架级接口（可以用它做任何事，但需要自己写顺序控制与响应处理）；SaReactorFilter 是 Sa-Token 提供的**开箱即用封装**，适合做鉴权这类规则化的横切逻辑。项目里两者都有使用，分别承担鉴权与限流，这是合理的组合。" },
        { t: "h", x: "4．追问 2：白名单与路由断言的问题（重点）" },
        { t: "p", x: "**白名单只有 3 条**（/user/login、/user/code、/actuator/**），意味着 /shop/**、/voucher/**、/blog/** 等所有查询接口都强制登录。对仿大众点评这类产品，未登录用户浏览商铺列表、查看店铺详情、浏览博客是**核心体验**——当前配置会导致未登录用户寸步难行。合理的做法是按「读写」或按具体路径细粒度放行（Sa-Token 支持 `SaRouter.match(\"/shop/**\").notMatch(...)` 这类链式规则），而不是一刀切。" },
        { t: "p", x: "**路由断言与控制器映射的不一致（高概率被追问）**：" },
        { t: "code", x: "网关断言（gateway-service/.../application.yaml:32）\n    order-route → predicates: [ Path=/order/** ]\n\n订单控制器实际映射（order-service/.../controller/VoucherOrderController.java:29,35）\n    @RequestMapping(\"/voucher-order\")\n    @PostMapping(\"seckill/{id}\")     →  真实路径为  /voucher-order/seckill/{id}\n\n同时 voucher-route 的断言是 Path=/voucher/**，\n而 /voucher-order/seckill/1 的第一段是 voucher-order，不等于 voucher —— 也匹配不上。\n\n而 README.md 5.5 又把 /voucher-order/seckill/{id} 列为对外可访问的订单接口路径。\n→ 三处无法自洽。" },
        { t: "p", x: "这个问题的正确应对方式不是回避，而是展现出你对自己网关配置的掌握：说明断言是**前缀匹配**、服务内 Controller 必须与之对齐；如果实测确认不通，修法是把断言改为 `Path=/voucher-order/**,/order/**`，或把 Controller 统一到 `/order` 前缀（二选一，不要两边都改）。面试前务必本地实测一次经 8081 的调用，这是最容易被现场验证的点。" },
        { t: "h", x: "5．追问 3：限流" },
        { t: "code", x: "仅 /agent/** 有限流：\n  gateway-service/.../filter/AgentRateLimitFilter.java:25-62\n    - implements GlobalFilter, Ordered；getOrder() == -10（:60-62）\n    - 仅拦截前缀 \"/agent/\"，其余直接放行（:38-40）\n    - 维度为 Sa-Token loginId：key = \"agent:rl:\" + loginId（:45-49）\n    - 超限返回 429 + 友好 JSON（:31,53）\n  gateway-service/.../limit/AgentTokenBucketLimiter.java\n    - Lua 脚本 limiter/token-bucket.lua 保证原子性\n    - 默认 capacity=10 / refill=10 每秒（:32-33）\n    - **Redis 异常时 fail-open 放行**（:46-51）" },
        { t: "p", x: "Spring Cloud Gateway 内置的 RequestRateLimiter / KeyResolver 在本项目中**未配置**（全仓无相关 yml 或 Bean）；除 /agent/** 之外的所有路由都没有限流。这意味着秒杀的入口限流实际是靠 Redis Lua 的库存预扣充当天然闸门（库存卖完即返回 1），而不是网关限流——这是一个可以讨论的设计取向（业务闸门 vs 流量闸门）。" },
        { t: "p", x: "Redis 故障时 fail-open 放行是一个明确的可用性优先取舍：宁可短时限流失效，也不让所有请求被拒。这个取向本身合理（限流不是核心业务），但要配套监控告警——否则 Redis 长时间不可用会变成「静默无限流」，无人察觉。" },
      ],
      sources: [
        "gateway-service/src/main/resources/application.yaml:12-57,79-88",
        "gateway-service/src/main/java/com/hmdp/gateway/config/SaTokenGatewayConfig.java:21-41",
        "gateway-service/src/main/java/com/hmdp/gateway/filter/AgentRateLimitFilter.java:25-62",
        "gateway-service/src/main/java/com/hmdp/gateway/limit/AgentTokenBucketLimiter.java（容量与 fail-open）",
        "gateway-service/src/main/resources/limiter/token-bucket.lua:1",
        "order-service/src/main/java/com/hmdp/order/controller/VoucherOrderController.java:29,35-38",
        "README.md:347-381（路由表）、:414-423（订单接口路径）",
      ],
      gap: {
        claim: "README.md:345 声明「所有接口统一通过网关 http://localhost:8081 访问（禁止绕过网关直连业务服务）」；5.5 将 /voucher-order/seckill/{id} 列为订单接口路径。",
        fact: "order-route 的断言是 Path=/order/**（gateway application.yaml:32），与 VoucherOrderController 的 @RequestMapping(\"/voucher-order\") 不匹配；voucher-route 的 Path=/voucher/** 同样匹配不上 /voucher-order/...。DSL 与实现存在不一致。",
        advice: "这是一条「面试官只要打开 yml 就能看到」的硬伤，且与 Q3 的核心考点直接相关。建议面试前先实测确认（curl 网关 8081 调秒杀接口），若不通就把断言补上 /voucher-order/** 并重新验证；面试时如被问到路由设计，主动说明「断言前缀必须与服务内 Controller 映射严格对齐」这个原则，比背诵路由表更能体现理解。",
      },
    },

    // ---------------- Q4 ----------------
    {
      cat: "认证鉴权", level: "进阶",
      title: "Sa-Token 会话是怎么在多个服务间共享的？网关校验通过后，下游服务怎么拿到当前用户？",
      focus: "考察点：分布式会话的实现原理、网关与下游的鉴权职责划分、越权风险与纵深防御、内网隔离的工程意识。",
      follows: [
        "下游服务为什么不配拦截器？这样做有什么风险？",
        "UserHolder.getUser() 是怎么拿到用户的？ThreadLocal 和 Sa-Token 会话是什么关系？",
        "业务服务端口直接暴露，怎么防止别人绕过网关直连？",
      ],
      blocks: [
        { t: "h", x: "1．会话共享机制：Redis 作为会话存储" },
        { t: "code", x: "依赖（版本统一为 sa-token 1.44.0，见父 pom.xml:41）\n  网关（WebFlux）：gateway-service/pom.xml:72-83\n      sa-token-reactor-spring-boot3-starter\n      sa-token-redis-jackson            ← 会话持久化到 Redis\n  业务服务（Servlet）：如 user-service/pom.xml:72-83\n      sa-token-spring-boot3-starter\n      sa-token-redis-jackson\n  common：common/pom.xml:81-86\n      sa-token-core（不绑定 Web 框架）\n\n连接配置：各服务 spring.data.redis 均指向同一实例\n  gateway-service/application.yaml:58-68  host localhost / port 6379 / password 520117\n  user-service/application.yaml:14-18       同上\n  （其余服务同）" },
        { t: "p", x: "原理：Sa-Token 默认把登录态存在内存（SaTokenDaoDefaultImpl），引入 sa-token-redis-jackson 后由 `SaTokenDaoRedisJackson` 接管，把「token → 会话数据」的映射以及 token 的过期时间写入 Redis。这样只要所有服务连的是**同一个 Redis**，无论请求被路由到哪个服务实例，都能读到同一份会话——这就是分布式会话的本质：**把有状态的会话从应用进程外置到共享存储**。" },
        { t: "p", x: "一个容易忽略的细节：gateway 用的是 reactor 版（因为 Spring Cloud Gateway 基于 WebFlux），业务服务用 servlet 版。common 模块只依赖 sa-token-core，并通过 `SaTokenConfig`（@ConditionalOnWebApplication(type = SERVLET)，经 AutoConfiguration.imports 注册，common/src/main/java/com/hmdp/config/SaTokenConfig.java:11-13）避免污染 WebFlux 环境——这是很规范的模块化处理。" },
        { t: "h", x: "2．下游如何拿到当前用户" },
        { t: "code", x: "common/src/main/java/com/hmdp/utils/UserHolder.java:24-39\npublic static UserDTO getUser() {\n    UserDTO user = userThreadLocal.get();        // ① 优先读 ThreadLocal\n    if (user != null) return user;\n    if (StpUtil.isLogin()) {                     // ② 委托 Sa-Token 会话\n        return (UserDTO) StpUtil.getSession().get(\"user\");\n    }\n    return null;\n}\n\n会话写入：user-service/.../service/impl/UserServiceImpl.java:113-120\n    StpUtil.login(user.getId());                              // :113 建立登录态\n    StpUtil.getSession().set(\"user\", userDTO);                // :117 把用户信息塞进会话\n    return Result.ok(StpUtil.getTokenValue());                // :120 返回 token" },
        { t: "p", x: "调用链：请求头携带 `Authorization: <token>`（sa-token.token-name 统一配置为 Authorization，各 application.yaml）→ 网关 SaReactorFilter 校验登录 → 请求被转发到下游服务时**请求头原样保留**（网关未配置任何移除/改写 header 的 filter）→ 下游服务通过 StpUtil 从 Redis 读到同一份会话，取出 user 对象。所以用户信息不需要在服务间显式传递，也不需要额外的 token 透传逻辑。" },
        { t: "p", x: "业务代码里一律使用 `UserHolder.getUser().getId()` 获取用户（如秒杀入口 VoucherOrderServiceImpl.java:94、退款校验 :219-224 都强制从登录态注入 userId）——**不接受前端传 userId**，这是防越权的关键设计。" },
        { t: "h", x: "3．追问 1：下游无二次鉴权的风险" },
        { t: "code", x: "全仓检索（业务服务侧）：\n  SaInterceptor / WebMvcConfigurer 注册拦截器  → 0 命中\n  @SaCheckLogin / @SaCheckPermission 注解        → 0 命中\n→ 业务服务不做任何鉴权，完全依赖网关。" },
        { t: "p", x: "风险：① **绕过网关即可访问全部业务接口**——任何能直连 8082-8086 的调用方（同网段的其它容器、误配置的 LB、内网横向移动的攻击者）都可以不带 token 调用接口。不过因为 UserHolder 拿不到用户会返回 null，涉及用户的接口会 NPE 报错而非越权成功——这是「意外的安全垫」，不能当作有意设计。② **内部调用无认证**——order→voucher 的 Feign 调用不带 token（VoucherFeignClient 没有 FeignAuthConfig；只有 agent-service 的 Feign 配了 token 透传配置），如果未来 voucher 也加鉴权，内部调用会被拒。③ 网关的白名单变更会直接改变所有服务的暴露面，缺乏纵深。" },
        { t: "h", x: "4．追问 3：防止绕过网关" },
        { t: "p", x: "代码层面目前**没有任何措施**——各服务的 server.port 是普通端口，直接监听所有网卡，没有内网隔离配置的证据。这属于部署架构问题，正确做法是：① 业务服务只监听内网地址（server.address 绑定内网网卡）或在容器编排层限制网络（K8s NetworkPolicy / 安全组只放行网关来源）；② 给内部接口加一层服务间认证（如 Feign 携带内部 token，或走 mTLS）；③ 业务服务也注册 SaInterceptor 做二次校验（成本是每请求多一次 Redis 查询，可用本地缓存优化），形成纵深防御。" },
        { t: "p", x: "面试时能主动指出「README 声明禁止绕过网关，但代码与部署配置层面并无强制手段，真正的隔离要靠网络层与内部认证」——这体现的是**安全边界意识**，比背诵 Sa-Token 用法更有价值。" },
      ],
      sources: [
        "common/src/main/java/com/hmdp/utils/UserHolder.java:24-39",
        "common/src/main/java/com/hmdp/config/SaTokenConfig.java:11-13 与 AutoConfiguration.imports",
        "user-service/src/main/java/com/hmdp/user/service/impl/UserServiceImpl.java:113-120",
        "user-service/src/main/java/com/hmdp/user/controller/UserController.java:62-69（登出）",
        "gateway-service/src/main/java/com/hmdp/gateway/config/SaTokenGatewayConfig.java:21-41",
        "各服务 pom.xml（sa-token starter 与 sa-token-redis-jackson）、父 pom.xml:41（版本 1.44.0）",
        "各服务 application.yaml（sa-token.token-name: Authorization、spring.data.redis 指向同一实例）",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:94,219-224",
      ],
    },

    // ---------------- Q5 ----------------
    {
      cat: "服务调用", level: "进阶",
      title: "服务间调用用的 OpenFeign，超时和降级是怎么配的？Fallback 返回失败后上游怎么处理？",
      focus: "考察点：Feign 与 CircuitBreaker 的集成关系、超时参数的合理性判断、fallback 语义与调用方行为的对齐（是否静默失败）。",
      follows: [
        "feign.circuitbreaker.enabled=true 是 fallback 生效的前提吗？",
        "connectTimeout 和 readTimeout 都是 5000ms，对秒杀链路合适吗？",
        "Fallback 返回 Result.fail(...) 之后，上游是怎么处理的？会不会静默失败？",
      ],
      blocks: [
        { t: "h", x: "1．服务间调用关系（全仓盘点）" },
        { t: "code", x: "order → voucher\n  @FeignClient(name = \"voucher-service\", fallback = VoucherFeignClientFallback.class)\n  order-service/.../feign/VoucherFeignClient.java:10-18\n    PUT  voucher/seckill/{id}/stock   → 扣减库存\n    GET  voucher/{id}                 → 查询优惠券详情\n\nsocial → user\n  @FeignClient(name = \"user-service\")        ← 无 fallback\n  social-service/.../feign/UserFeignClient.java:16,22-29\n    GET /user/{id}、GET /user/list\n\nagent → voucher / shop / order / rag         （配 FeignAuthConfig 透传 token，本次范围外）\n\n@EnableFeignClients 出现在 user/shop/voucher/order/social/rag 六个启动类上。" },
        { t: "h", x: "2．超时配置" },
        { t: "code", x: "order-service/src/main/resources/application.yaml:119-127    ← 全仓唯一显式 Feign 超时配置\nfeign:\n  circuitbreaker:\n    enabled: true\n  client:\n    config:\n      default:\n        connectTimeout: 5000\n        readTimeout: 5000\n\nuser / shop / voucher / social 四个服务**未配置** Feign 超时，使用框架默认值。" },
        { t: "p", x: "connectTimeout 是建立 TCP 连接的超时（含从 Nacos 拿到实例后的连接过程），readTimeout 是连接建立后等待响应的时间。两者分开配置的原因不同：连接超时通常反映网络/实例不可达（应快速失败），读超时反映下游处理耗时（应按业务 SLA 设定）。" },
        { t: "h", x: "3．追问 1：circuitbreaker.enabled 是前提吗" },
        { t: "p", x: "是的。`@FeignClient` 的 `fallback` 属性是由 Spring Cloud CircuitBreaker 的 Feign 集成提供的：开启 `feign.circuitbreaker.enabled=true` 后，Feign 的调用会被包装进一个 CircuitBreaker 装饰器，异常时转而调用 fallback 实现。未开启时，fallback 属性会被忽略，异常直接抛给调用方。本项目的 order-service 配了 true，且 VoucherFeignClient 指定了 fallback 类，所以降级生效；而 social 的 UserFeignClient 既未指定 fallback，social-service 也未开 circuitbreaker（application.yaml 无 feign 段），调用失败会直接抛异常。" },
        { t: "p", x: "另外要说明：Spring Cloud 2022.x 中 CircuitBreaker 的默认实现是 Spring Retry 的 `RetryableCircuitBreaker` 或需引入 Resilience4j，具体实现取决于引入的依赖。本项目的 fallback 生效依赖的是 spring-cloud-starter-circuitbreaker 相关传递依赖，其断路器语义（阈值、半开状态）使用的是**默认配置**，项目中未做任何自定义（未配置任何 CircuitBreaker 实例参数）——这是可以改进的点：默认阈值不一定适配秒杀场景。" },
        { t: "h", x: "4．追问 2：5000ms 对秒杀链路合适吗" },
        { t: "p", x: "偏大，且**位置很关键**。这个 Feign 调用发生在 `SeckillOrderConsumer` 的 MQ 消费线程里（SeckillOrderConsumer.java:116），不是秒杀入口。也就是说：每一次扣库存最多可能阻塞消费者线程 5 秒。而消费端本身就是整条链路的吞吐瓶颈（方案文档测算 500~1000 msg/s/节点），一次 5 秒的阻塞会直接让该消费线程在这段时间内什么都做不了，积压迅速累积。" },
        { t: "p", x: "更合适的配置是 1~2 秒并配合快速失败与重试策略（MQ 本身已有重试机制，不必靠长超时硬等）。对比参考：agent-service 侧的 Feign 工具调用上限就是 2 秒（kb_search 放宽到 5 秒）。所以回答这个问题时，重要的是说清「超时值要与调用发生的线程模型和下游 SLA 匹配」，而不是背一个数字。" },
        { t: "h", x: "5．追问 3：Fallback 之后上游怎么办（值得深挖）" },
        { t: "code", x: "order-service/.../fallback/VoucherFeignClientFallback.java:10-23\n@Override\npublic Result deductStock(Long voucherId) {\n    log.warn(\"voucher-service服务不可用，扣减库存降级处理: voucherId={}\", voucherId);\n    return Result.fail(\"库存服务暂时不可用，订单将异步处理\");      // ← 返回值\n}\n\n消费端处理（SeckillOrderConsumer.java:116-122）\nResult deductResult = voucherFeignClient.deductStock(voucherId);\nif (!deductResult.getSuccess()) {\n    log.error(\"扣减库存失败: voucherId={}, result={}\", voucherId, deductResult.getErrorMsg());\n    rollbackRedisData(voucherId, userId);      // 回补 Redis 库存 + 移除已购标记\n    seckillMetrics.incrementMqConsumeFail();\n    return;                                    // ← 直接返回，不重试\n}" },
        { t: "p", x: "这里有一个**文案与行为不一致**的问题：fallback 返回的错误信息是「库存服务暂时不可用，订单将异步处理」，但它不会异步处理任何东西。消费端收到失败结果后执行的是「回补 Redis 库存 + 移除用户已购标记 + 直接 return」——消息被静默丢弃，订单**永远不会创建**。用户侧的表现是：秒杀时看到了成功（拿到 orderId），但订单永远查不到，且 Redis 库存被回补（可以再次尝试购买）。" },
        { t: "p", x: "这属于「**降级即失败**」：降级在这里并没有提供有意义的降级能力，反而把一次本可重试的系统异常变成了静默的业务失败。更合理的处理有两种：① 若判断为**瞬时故障**（网络抖动），应当 throw 让 MQ 重试，而不是 return（当前代码选择 return，等价于放弃重试）；② 若确实要降级，应当把订单写入 Redis 的待处理队列（seckill:order:queue 本就存在，只是无人消费），由对账任务后续补偿——这才配得上「订单将异步处理」这句文案。" },
        { t: "p", x: "这是一个非常好的追问落点：它能同时考察「是否读过自己写的 fallback」「是否理解降级与重试的语义差别」「能否发现文案与实现脱节」。建议面试前至少把 fallback 的文案改成与实际行为一致，或把行为改成与文案一致。" },
      ],
      sources: [
        "order-service/src/main/java/com/hmdp/order/feign/VoucherFeignClient.java:10-18",
        "order-service/src/main/java/com/hmdp/order/fallback/VoucherFeignClientFallback.java:10-23",
        "order-service/src/main/java/com/hmdp/order/mq/SeckillOrderConsumer.java:116-122,176-184",
        "order-service/src/main/resources/application.yaml:119-127",
        "social-service/src/main/java/com/hmdp/social/feign/UserFeignClient.java:16-29",
        "docs/perf-plan/架构演进与性能优化落地方案.md:47-56（消费端吞吐基线）、:36（P1-1 五次串行 IO）",
      ],
    },

    // ---------------- Q6 ----------------
    {
      cat: "分布式事务", level: "深入",
      title: "Seata 在你项目里到底启用了吗？「Seata 后优化为 Redis+Lua+RocketMQ」具体指什么？",
      focus: "考察点：分布式事务方案的演进叙事、配置冲突的排查能力、对「配置存在 ≠ 生效」的辨析、AT 模式原理与替代方案的取舍。",
      follows: [
        "bootstrap.yaml 配的是 hmdp-group、application.yaml 配的是 my_test_tx_group，最终哪个生效？为什么？",
        "voucher-service 的 pom 里没有 seata 依赖，但 yml 写了 seata.enabled: true，会发生什么？",
        "@GlobalTransactional 现在标在哪个方法上？这个方法还在秒杀主链路上吗？",
      ],
      blocks: [
        { t: "h", x: "1．先给结论：简历方向属实，但「移除」的说法不准确" },
        { t: "p", x: "秒杀主链路**确实已经不依赖 Seata**，改为「Redis Lua 预扣 + RocketMQ 异步」的最终一致方案——这一点简历描述是成立的。但不准确的是「优化为」所暗示的「已替换/已移除」：Seata 仍处于 `enabled: true` 状态，依赖仍在，注解仍在，只是**当前没有走它**。" },
        { t: "h", x: "2．追问 1：两套事务组配置的冲突（关键）" },
        { t: "code", x: "order-service/src/main/resources/bootstrap.yaml:24-41\nseata:\n  tx-service-group: hmdp-group              # ← 事务组 A\n  cluster: default\n  service:\n    vgroup-mapping:\n      hmdp-group: default\n    grouplist:\n      default: localhost:8091\n  registry: { type: file }\n  config:   { type: file }\n\norder-service/src/main/resources/application.yaml:48-63\nseata:\n  enabled: true\n  application-id: ${spring.application.name}\n  tx-service-group: my_test_tx_group        # ← 事务组 B（冲突）\n  service:\n    vgroupMapping:\n      my_test_tx_group: default\n    grouplist:\n      default: 127.0.0.1:8091\n  data-source-proxy-mode: AT\n\nvoucher-service 同构：bootstrap.yaml:24-40（hmdp-group）+ application.yaml:40-55（my_test_tx_group）" },
        { t: "p", x: "Spring Boot 的配置优先级规则里，**application.yaml 的优先级高于 bootstrap.yaml**（bootstrap 上下文加载更早，但 application 的属性源覆盖后者）。因此最终生效的是 `my_test_tx_group`，而不是 CLAUDE.md:75 与 README 7.3 节所声称的 `hmdp-group`。这是一个典型「文档与实现不一致」的问题。两套配置必须统一——若保持现状，Seata Server 侧若按 hmdp-group 建组，客户端会因找不到事务组而失败。修法：删除 bootstrap.yaml 里的 seata 段（或删除 application.yaml 里的），只保留一处。" },
        { t: "h", x: "3．追问 2：voucher-service 的死配置" },
        { t: "code", x: "seata 依赖的实际引入位置：\n  order-service/pom.xml:70-81   seata-spring-boot-starter（排除 druid）\n  voucher-service/pom.xml        → 无任何 io.seata 依赖\n\n父 pom.xml:37,87-92             → 只有 dependencyManagement 版本管理（1.7.0），无模块默认引入\n\n但 voucher-service/src/main/resources/application.yaml:40-55 却写了：\n  seata:\n    enabled: true\n    tx-service-group: my_test_tx_group\n    ...\n  # 以及 management.endpoints.web.exposure.include: seata,...（:89-96）" },
        { t: "p", x: "因为类路径上没有 seata 的 starter，Seata 的自动配置根本不会被触发，这段配置**没有任何代码去消费它**——属于死配置。同理，voucher 的 Actuator 里 include 了 `seata` 端点，但该端点也不存在（order-service 的 application.yaml:96-104 就把这段注释掉了，并注明理由「移除 'seata'，因为不存在这个端点」——说明这个问题在 order 侧已被发现并修正过一次，但没有同步到 voucher）。" },
        { t: "p", x: "这个细节的价值在于：它说明项目在「配置与依赖的一致性」上缺乏系统性检查。面试时可以借此提出改进建议（如引入配置校验、或在 CI 中做依赖与配置的交叉检查）。" },
        { t: "h", x: "4．追问 3：@GlobalTransactional 的位置" },
        { t: "code", x: "order-service/.../service/impl/VoucherOrderServiceImpl.java:135-161\n/**\n * 创建优惠券订单（供传统同步流程使用）\n *\n * 注意：此方法在秒杀场景中已由异步流程替代，仅保留用于兼容传统调用。\n */\n@GlobalTransactional(name = \"createVoucherOrder\", rollbackFor = Exception.class)\n@Transactional\npublic void createVoucherOrder(VoucherOrder voucherOrder) {\n    Long count = query().eq(\"user_id\", userId).eq(\"voucher_id\", ...).count();\n    if (count > 0) { log.error(\"用户已经购买过一次！\"); return; }\n    Result result = voucherFeignClient.deductStock(voucherOrder.getVoucherId());   // 跨服务调用\n    if (!result.getSuccess()) { log.error(\"库存不足！\"); return; }\n    save(voucherOrder);\n}\n\n全仓 grep @GlobalTransactional  →  仅此一处。\n秒杀主入口 seckillVoucher（:88-133）**没有**该注解。" },
        { t: "p", x: "该方法就是 Seata 在本项目中唯一的实际落点：它做的是「跨服务扣库存 + 本地写订单」，正是 AT 模式要解决的典型场景。方法的 Javadoc 自述它已被异步流程替代、仅用于兼容传统调用——**即这条 Seata 链路在秒杀场景下实际上是死路径**（没有任何 Controller 调用它）。" },
        { t: "h", x: "5．AT 模式原理与替代方案取舍（深挖）" },
        { t: "code", x: "Seata AT 模式核心机制\n  1. 全局事务开启 → 生成全局唯一 XID，通过 RPC 上下文传播到各参与方\n  2. 每个分支事务执行前，先查询业务数据的前镜像（before image）\n  3. 业务 SQL 与 undo_log 记录**在同一个本地事务**中提交\n       undo_log: { xid, branch_id, rollback_info(前后镜像), ... }\n  4. 全部成功 → 异步清理 undo_log；任一失败 → TC 驱动各分支执行回滚\n  5. 回滚 = 用 before image 反向补偿（UPDATE 回原值），而非数据库回滚\n\n本项目证据：docs/SQL/undo_log.sql（回滚日志表，含 ux_undo_log(xid, branch_id)）\n            order-service/application.yaml:63  data-source-proxy-mode: AT\n            order-service/pom.xml:70-81         seata-spring-boot-starter" },
        { t: "p", x: "AT 模式的优点是对业务无侵入（只需一个注解，SQL 由数据源代理拦截）；代价是**全局锁**（TC 维护的行锁在全局事务提交前不释放，高并发下成为瓶颈）、每个分支都要写 undo_log（额外 IO）、以及必须有一个 Seata Server（TC）作为单点组件。在秒杀这种「高并发 + 热点行（同一张券的库存）」的场景下，AT 的全局锁会让库存行的争用急剧放大——这正是项目放弃 Seata、改用「Redis 预扣把并发挡在 DB 之外 + MQ 异步最终一致」的根本原因。" },
        { t: "p", x: "替代方案对比：① **TCC**——性能优于 AT（无全局锁、无需 undo_log），但需要业务实现 try/confirm/cancel 三个接口，侵入性强、开发成本高；② **可靠消息最终一致**（本项目所选）——把强一致降级为最终一致，用 Redis 做前置校验 + MQ 做异步落库，吞吐最高，代价是中间态可见、需要补偿机制；③ **本地消息表/事务消息**——适用于「本地写 + 发消息」的原子性，本项目尚未落地（见秒杀分册 Q10）。" },
        { t: "p", x: "如何完整回答「Seata 后优化为 Redis+Lua+RocketMQ」：先用一句话点明演进动因（AT 的全局锁与 undo_log 在高并发热点场景下不可接受），再讲清当前方案（Redis 做原子预扣承担并发、MQ 做异步与重试、消费端幂等保证不重复），最后坦诚说明 Seata 尚未清理干净（两处事务组冲突、voucher 死配置、遗留注解），并给出清理清单。这样既讲了架构判断，又不会在追问下翻车。" },
      ],
      sources: [
        "order-service/src/main/resources/bootstrap.yaml:24-41（hmdp-group）",
        "order-service/src/main/resources/application.yaml:48-63,96-104（my_test_tx_group + 被注释的 seata 端点）",
        "voucher-service/src/main/resources/bootstrap.yaml:24-40 与 application.yaml:40-55,89-96（死配置）",
        "order-service/src/main/java/com/hmdp/order/service/impl/VoucherOrderServiceImpl.java:135-161（唯一 @GlobalTransactional）",
        "order-service/pom.xml:70-81（seata-spring-boot-starter，仅 order 引入）",
        "父 pom.xml:37,87-92（seata 1.7.0 版本管理）",
        "docs/SQL/undo_log.sql:1-12（AT 模式回滚日志表）",
        "README.md:584-603（Seata 配置示例，只展示了 hmdp-group 版）",
        "CLAUDE.md:75（声明事务组为 hmdp-group）",
      ],
      gap: {
        claim: "简历：微服务拆分 6 个：Nacos 注册发现与配置中心，Gateway 统一路由，OpenFeign 调用，Seata 分布式事务（后优化为 Redis+Lua + RocketMQ）。",
        fact: "演进方向属实——秒杀主链路确实已不使用 Seata，改走 Redis+Lua+RocketMQ 最终一致。但「优化为」容易让人理解为「已替换/已移除」，实际现状是：Seata enabled: true 仍在（order/voucher 两处 yml）、依赖仍在（order-service/pom.xml:70-81）、唯一一处 @GlobalTransactional 仍标注在一个已废弃的方法上（VoucherOrderServiceImpl.java:143，注释自陈「仅保留用于兼容传统调用」，且无调用方）。另有配置缺陷：bootstrap 的 hmdp-group 与 application 的 my_test_tx_group 冲突（后者优先级更高，实际生效），voucher-service 声明 seata.enabled 却无对应依赖（死配置）。",
        advice: "这一题的应对策略是「承认现状 + 讲清演进动因 + 给出清理清单」，这比含糊地说「已经换成 Redis+Lua 了」安全得多。建议面试前做一次小清理（三选一或全做）：① 统一 Seata 事务组配置（删掉 bootstrap 或 application 中的一处）；② 删除 voucher-service 中的 seata 死配置与 seata Actuator 端点；③ 若确定不再需要 Seata，则彻底移除依赖 + 注解 + undo_log 表。做完之后，「我们评估后认为 AT 模式在高并发热点场景下的全局锁不可接受，因此改为 Redis 预扣 + MQ 最终一致」就是一段非常完整、有技术判断力的架构演进叙述。",
      },
    },
  ],
};
